### ISSUE TITLE
CentOS Issue

### ISSUE THREAD

**Issue by fletchette** [hydrabolt/discord.js#101]
When running Discord.js in CentOS I get this error

```javascript
/home/server/myuser/node_modules/discord.js/lib/Voice/StreamIntent.js:9
f (typeof superClass !== "function" && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (/home/server/myuser/node_modules/discord.js/lib/Voice/StreamIntent.js:9:113)
    at /home/server/myuser/node_modules/discord.js/lib/Voice/StreamIntent.js:16:2
    at Object.<anonymous> (/home/server/myuser/node_modules/discord.js/lib/Voice/StreamIntent.js:25:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/server/myuser/node_modules/discord.js/lib/Voice/VoiceConnection.js:38:21)
```

**Comment by hydrabolt** [comment]
You require node 12.0+

**Comment by fletchette** [comment]
Running node v.5.2.0

**Comment by khionu** [comment]
Try using the LTS? CentOS doesn't do good with Bleeding Edge

**Comment by hydrabolt** [comment]
Are you SURE that its 5.2.0? I handled a similar issue where someone had
5.2.0 installed but they were using 0.10

**Comment by khionu** [comment]
Try uninstalling and compiling from source: https://nodejs.org/dist/v4.2.4/node-v4.2.4-linux-x64.tar.gz

**Comment by khionu** [comment]
4.2.4 = Current LTS

**Comment by fletchette** [comment]
node -v prints v.5.2.0
