### ISSUE TITLE
[indev] Cannot read property 'error' of undefined (in InternalClient.js)

### ISSUE THREAD

**Issue by MadScripter** [hydrabolt/discord.js#103]
I'm randomly getting this error sometimes:

```
C:\Users\MadScripter\Desktop\#PROGRAMMING\NodeJS\Projects\Discord_Bot\node_modules\discord.js\lib\Client\InternalClient.js:135
					error.response.error.status = 429;
					              ^

TypeError: Cannot read property 'error' of undefined
    at C:\Users\MadScripter\Desktop\#PROGRAMMING\NodeJS\Projects\Discord_Bot\node_modules\discord.js\lib\Client\InternalClient.js:135:20
    at Request.callback (C:\Users\MadScripter\Desktop\#PROGRAMMING\NodeJS\Projects\Discord_Bot\node_modules\superagent\lib\node\index.js:784:12)
    at ClientRequest.<anonymous> (C:\Users\MadScripter\Desktop\#PROGRAMMING\NodeJS\Projects\Discord_Bot\node_modules\superagent\lib\node\index.js:738:10)
    at emitOne (events.js:78:13)
    at ClientRequest.emit (events.js:170:7)
    at TLSSocket.socketErrorListener (_http_client.js:266:9)
    at emitOne (events.js:78:13)
    at TLSSocket.emit (events.js:170:7)
    at connectErrorNT (net.js:999:8)
    at nextTickCallbackWith2Args (node.js:455:9)
```

**Comment by hydrabolt** [comment]
Fixed
