### ISSUE TITLE
WebSocketManager this.ws null on destroy

### ISSUE THREAD

**Issue by vstrand** [hydrabolt/discord.js#1095]
```javascript
const Discord = require('discord.js');
const bot = new Discord.Client();

const token = 'my-token';
bot
  .login(token)
  .then(() => {
    console.log('Success');
  })
  .catch((err) => {
    console.log(`Error ${err}`);
  });

process.on('exit', () => {
  bot.destroy();
});
process.on('SIGINT', process.exit);
```
If you read the token from a configuration file and it's value is anything other than a string, the login method will reject with an error before it exits the Node application (as expected). If I catch process exit event and call bot.destroy() in the event callback I get an error:
```
/Users/<username>/Documents/<project-name>/node_modules/discord.js/src/client/websocket/WebSocketManager.js:158
    this.ws.close(1000);
           ^

TypeError: Cannot read property 'close' of null
    at WebSocketManager.destroy (/Users/<username>/Documents/<project-name>/node_modules/discord.js/src/client/websocket/WebSocketManager.js:158:12)
    at ClientManager.destroy (/Users/<username>/Documents/<project-name>/node_modules/discord.js/src/client/ClientManager.js:55:20)
    at Client.destroy (/Users/<username>/Documents/<project-name>/node_modules/discord.js/src/client/Client.js:252:25)
    at process.on (/Users/<username>/Documents/<project-name>/src/index.js:26:7)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
```
The WebSocketManager sets this.ws to null initially and assigns it a new WebSocket(gateway); when its _connect method is executed. The proposed fix is to check for a null value, or that it actually has a property close in the WebSocketManager's destroy method.
```javascript
destroy() {
    if (this.ws !== null) {
        this.ws.close(1000);
    }
    this._queue = [];
    this.status = Constants.Status.IDLE;
}
```

**Comment by GusCaplan** [comment]
i can throw this fix in my ws rewrite. (see #1088) thanks for bringing this up!
