### ISSUE TITLE
Unable to get the bot to join a certain voiceChannel.

### ISSUE THREAD

**Issue by TotomInc** [hydrabolt/discord.js#1130]
Hi,

I'm running the bot under Cloud9 Linux workspace if this can help. The bot can't join a voiceChannel, it throws always the same error:

```
client.joinVoiceChannel(client.channels.get("name", "bot"), function() {
           ^

TypeError: client.joinVoiceChannel is not a function
    at Client.client.on (/home/ubuntu/workspace/bot.js:14:12)
    at emitNone (events.js:91:20)
    at Client.emit (events.js:185:7)
    at WebSocketManager._emitReady (/home/ubuntu/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:325:17)
    at WebSocketManager.checkIfReady (/home/ubuntu/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:14)
    at GuildCreateHandler.handle (/home/ubuntu/workspace/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/home/ubuntu/workspace/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/home/ubuntu/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:273:31)
    at WebSocket.onMessage (/home/ubuntu/workspace/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
```

I'm going to think that this function really not exists, but I have read that a lot of users are able to use it. Why I can't use it? Looks like Discord.js is not fully installed. I have created some commands, the bot answer to them. But I can't get this bot joining my voice channel because `joinVoiceChannel is not a function`. Tried to uninstall everything, reinstall with node-opus, still doesn't work.

Here is my bot code:

```
const Discord = require('discord.js'),
    token = '***',
    client = new Discord.Client();

client.on('ready', () => {
    client.joinVoiceChannel(client.channels.get("name", "bot"), function() {
        console.log("Joining #bot");
    });
});

client.login(token);
```

I don't know if this is the right place to ask for help about code stuff, if not, please let me know.

Thanks! 😃

**Comment by bdistin** [comment]
It appears you are working with Discord.JS v8 code, which is no longer supported. Although, from that error, it seems like you have installed a more current version of D.JS.

You can find the docs for the current version of D.JS here: http://discord.js.org
You can find library support in the Official D.JS Discord Guild here: https://discord.gg/bRCvFy9

**Comment by TotomInc** [comment]
That's right! I was using an old documentation, thanks for pointing out this mistake. Going to test changes, but it should work now.
