### ISSUE TITLE
Crashes app when hitting Discord rate limit

### ISSUE THREAD

**Issue by ak505188** [hydrabolt/discord.js#1181]
Get this error when I get a 429 from Discord.
Running in a Docker container on a Raspberry Pi 3. Node version is 7.4.0.

```
/usr/src/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79
            this.restManager.client.setTimeout(() => {
                                    ^
TypeError: this.restManager.client.setTimeout is not a function
    at item.request.gen.end (/usr/src/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:37)
    at Request.callback (/usr/src/app/node_modules/superagent/lib/node/index.js:619:12)
    at /usr/src/app/node_modules/superagent/lib/node/index.js:795:18
    at Stream.<anonymous> (/usr/src/app/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (/usr/src/app/node_modules/superagent/lib/node/utils.js:112:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This was on the latest release. Hit the same bug on the latest commit as well. Here's the stack trace.
```
/usr/src/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68
            this.restManager.client.setTimeout(
                                    ^

TypeError: this.restManager.client.setTimeout is not a function
    at item.request.gen.end (/usr/src/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:37)
    at Request.callback (/usr/src/app/node_modules/superagent/lib/node/index.js:652:14)
    at /usr/src/app/node_modules/superagent/lib/node/index.js:866:18
    at Stream.<anonymous> (/usr/src/app/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (/usr/src/app/node_modules/superagent/lib/node/unzip.js:53:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Gawdl3y** [comment]
No idea how this is happening.

**Comment by mrkishi** [comment]
I've experienced the same. It happens when using `WebhookClient`: it initializes a `RESTManager` with a reference to itself, but it isn't an actual `Client` and doesn't have a `setTimeout`.

**Comment by GusCaplan** [comment]
I will fix this on Monday unless someone beats me to it, thanks for reporting this :)

**Comment by mrkishi** [comment]
Hey @GusCaplan and @Gawdl3y, thank you for the fix.

Quick question: when could we expect this to be published to npm? Is it maybe a "cherry-pick as a patch version bump" case?

**Comment by GusCaplan** [comment]
you can just do `npm i hydrabolt/discord.js`

**Comment by mrkishi** [comment]
But then I'd have to keep track of every breaking change in `master` -- or are there none?

**Comment by GusCaplan** [comment]
not at the moment, we are gearing for 11.1.0 release right now.
