### ISSUE TITLE
Sample code not working with bufferutil installed.

### ISSUE THREAD

**Issue by IreliaHasHands** [hydrabolt/discord.js#1184]
**Node Version:** 7.2.1

Sample code works fine until I install **bufferutil** module. 

```
/home/hands/node/discordbot/node_modules/ws/lib/Sender.js:211
      bufferUtil.mask(data, mask, outputBuffer, dataOffset, dataLength);
                ^

TypeError: Cannot read property 'mask' of undefined
    at Sender.frameAndSend (/home/hands/node/discordbot/node_modules/ws/lib/Sender.js:211:17)
    at /home/hands/node/discordbot/node_modules/ws/lib/Sender.js:119:12
    at Sender.flush (/home/hands/node/discordbot/node_modules/ws/lib/Sender.js:265:33)
    at Sender.send (/home/hands/node/discordbot/node_modules/ws/lib/Sender.js:135:8)
    at WebSocket.send (/home/hands/node/discordbot/node_modules/ws/lib/WebSocket.js:267:18)
    at WebSocketManager._send (/home/hands/node/discordbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:166:15)
    at WebSocketManager.doQueue (/home/hands/node/discordbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:178:10)
    at WebSocketManager.send (/home/hands/node/discordbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:154:10)
    at WebSocketManager._sendNewIdentify (/home/hands/node/discordbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:225:10)
    at WebSocketManager.eventOpen (/home/hands/node/discordbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:190:15)
```

**Comment by Gawdl3y** [comment]
Looks like a ws issue. Do you have 2.0.0 installed? `npm ls bufferutil`

**Comment by IreliaHasHands** [comment]
I have bufferutil 2.0.1 installed.

**Comment by Gawdl3y** [comment]
What "sample code" are you using? The main example in the readme/on the website?

**Comment by IreliaHasHands** [comment]
The "example usage" Ping Pong.

**Comment by Gawdl3y** [comment]
I'm unable to reproduce this error. It's working completely fine for me - in fact, my test bot is 100% functional as well.
Ensure your `ws` is also >= v2.0.0.

**Comment by Gawdl3y** [comment]
Just gave it a shot, and it looks like your error is, in fact, caused by `ws` < 2.0.0. The master branch of discord.js requires `ws` 2.0.0 or newer.

**Comment by IreliaHasHands** [comment]
`npm ls bufferutil` showed that I had bufferutil 2.0.1 installed.  I will try getting 2.0.0.

**Comment by Gawdl3y** [comment]
Please fully read my previous comment. You're still using `ws` v1, and trying to use `bufferutil` v2. `ws` v1 will only work with `bufferutil` v1 - whereas `ws` v2 will work with any version of `bufferutil` (but you should use v2).

**Comment by IreliaHasHands** [comment]
I'm just following the commands from the readme, and using the example usage from the readme.

**Comment by Gawdl3y** [comment]
Yes, and you're looking at the master branch's readme, but using an older version of discord.js that doesn't require ws 2.0.0+, but rather 1.1.1+. You have to use bufferutil v1.0.0 for ws 1.1.1, not v2.0.0. Either downgrade bufferutil, or upgrade ws.

**Comment by IreliaHasHands** [comment]
I understand now.  Thanks for the support.
