### ISSUE TITLE
USE_EXTERNAL_EMOJIS and MANAGE_ROLES permissions not recognize

### ISSUE THREAD

**Issue by EmmanuelVlad** [hydrabolt/discord.js#1232]
hey, whenever I try to check the permission USE_EXTERNAL_EMOJIS or MANAGE_ROLES it returns me this
```Error: Invalid permission string or number.
0|reaktor  |     at ClientDataResolver.resolvePermission (C:\Users\emman\Desktop\reaktor\node_modules\discord.js\src\client\ClientDataResolver.js:192:65)
0|reaktor  |     at Role.hasPermission (C:\Users\emman\Desktop\reaktor\node_modules\discord.js\src\structures\Role.js:154:39)
0|reaktor  |     at Client.reaktor.on.message (C:\Users\emman\Desktop\reaktor\app.js:404:54)
0|reaktor  |     at emitOne (events.js:96:13)
0|reaktor  |     at Client.emit (events.js:189:7)
0|reaktor  |     at MessageCreateHandler.handle (C:\Users\emman\Desktop\reaktor\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
0|reaktor  |     at WebSocketPacketManager.handle (C:\Users\emman\Desktop\reaktor\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:120:65)
0|reaktor  |     at WebSocketManager.eventMessage (C:\Users\emman\Desktop\reaktor\node_modules\discord.js\src\client\websocket\WebSocketManager.js:273:31)
0|reaktor  |     at WebSocket.onMessage (C:\Users\emman\Desktop\reaktor\node_modules\ws\lib\WebSocket.js:442:14)
0|reaktor  |     at emitTwo (events.js:106:13)```

only of those two.

**Comment by 1Computer1** [comment]
Those are not the actual name of the permissions.
See https://discord.js.org/#/docs/main/master/typedef/PermissionResolvable.

**Comment by EmmanuelVlad** [comment]
oh man, I was actually browsing it and I didn't even compare to this: https://discordapp.com/developers/docs/topics/permissions
I feel so dumb...

Thank you! 👍
