### ISSUE TITLE
Issue while starting a bot

### ISSUE THREAD

**Issue by MrSouth** [hydrabolt/discord.js#1242]
So, i are new on Discord.js and in Javascript, i see various youtube tutorials, and i saw one that looks good.
When i started the bot in CMD this error appears:

 C:\Users\Gabriel\Desktop\My Bot>node bot.js
C:\Users\Gabriel\Desktop\My Bot\bot.js:1
(function (exports, require, module, __filename, __dirname) { const Discord = require(Discord.js);
                                                                                      ^

ReferenceError: Discord is not defined
    at Object.<anonymous> (C:\Users\Gabriel\Desktop\My Bot\bot.js:1:87)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

C:\Users\Gabriel\Desktop\My Bot>PAUSE

**Comment by GusCaplan** [comment]
`require('discord.js')` is your issue.

please take the time to learn how javascript and node.js work. thx

**Comment by MrSouth** [comment]
@GusCaplan Thx :D
