### ISSUE TITLE
Keep getting this error in the log when doing "npm install discord.js --save"

### ISSUE THREAD

**Issue by JMccormick264** [hydrabolt/discord.js#1252]
```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\legit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.js' ]
2 info using npm@4.4.0
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData discord.js@github:hydrabolt/discord.js#indev
8 silly fetchOtherPackageData discord.js@github:hydrabolt/discord.js#indev
9 silly cache add args [ 'discord.js@github:hydrabolt/discord.js#indev', null ]
10 verbose cache add spec discord.js@github:hydrabolt/discord.js#indev
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'discord.js@github:hydrabolt/discord.js#indev',
11 silly cache add   scope: null,
11 silly cache add   escapedName: 'discord.js',
11 silly cache add   name: 'discord.js',
11 silly cache add   rawSpec: 'github:hydrabolt/discord.js#indev',
11 silly cache add   spec: 'github:hydrabolt/discord.js#indev',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:hydrabolt/discord.js.git#indev',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/hydrabolt/discord.js.git#indev',
11 silly cache add      httpsUrl: 'git+https://github.com/hydrabolt/discord.js.git#indev',
11 silly cache add      gitUrl: 'git://github.com/hydrabolt/discord.js.git#indev',
11 silly cache add      shortcut: 'github:hydrabolt/discord.js#indev',
11 silly cache add      directUrl: 'https://raw.githubusercontent.com/hydrabolt/discord.js/indev/package.json' } }
12 verbose addRemoteGit caching github:hydrabolt/discord.js#indev
13 verbose addRemoteGit hydrabolt/discord.js#indev is a repository hosted by github
14 silly tryGitProto attempting to clone git://github.com/hydrabolt/discord.js.git#indev
15 silly tryClone cloning hydrabolt/discord.js#indev via git://github.com/hydrabolt/discord.js.git#indev
16 verbose tryClone git-github-com-hydrabolt-discord-js-git-indev-58d7434c not in flight; caching
17 verbose correctMkdir C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
18 info git [ 'config', '--get', 'remote.origin.url' ]
19 silly validateExistingRemote hydrabolt/discord.js#indev remote.origin.url: git://github.com/hydrabolt/discord.js.git
20 verbose validateExistingRemote hydrabolt/discord.js#indev is updating existing cached remote C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-58d7434c
21 info git [ 'fetch', '-a', 'origin' ]
22 verbose updateRemote git fetch -a origin (git://github.com/hydrabolt/discord.js.git)
23 verbose setPermissions hydrabolt/discord.js#indev skipping chownr on Windows
24 verbose resolveHead hydrabolt/discord.js#indev original treeish: indev
25 info git [ 'rev-list', '-n1', 'indev' ]
26 error git rev-list -n1 indev: fatal: ambiguous argument 'indev': unknown revision or path not in the working tree.
26 error git rev-list -n1 indev: Use '--' to separate paths from revisions, like this:
26 error git rev-list -n1 indev: 'git <command> [<revision>...] -- [<file>...]'
27 silly tryHTTPS attempting to clone git+https://github.com/hydrabolt/discord.js.git#indev
28 silly tryClone cloning hydrabolt/discord.js#indev via git+https://github.com/hydrabolt/discord.js.git#indev
29 verbose tryClone git-https-github-com-hydrabolt-discord-js-git-indev-16bb84c4 not in flight; caching
30 verbose correctMkdir C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
31 info git [ 'config', '--get', 'remote.origin.url' ]
32 silly validateExistingRemote hydrabolt/discord.js#indev remote.origin.url: https://github.com/hydrabolt/discord.js.git
33 verbose validateExistingRemote hydrabolt/discord.js#indev is updating existing cached remote C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-hydrabolt-discord-js-git-indev-16bb84c4
34 info git [ 'fetch', '-a', 'origin' ]
35 verbose updateRemote git fetch -a origin (https://github.com/hydrabolt/discord.js.git)
36 verbose setPermissions hydrabolt/discord.js#indev skipping chownr on Windows
37 verbose resolveHead hydrabolt/discord.js#indev original treeish: indev
38 info git [ 'rev-list', '-n1', 'indev' ]
39 error git rev-list -n1 indev: fatal: ambiguous argument 'indev': unknown revision or path not in the working tree.
39 error git rev-list -n1 indev: Use '--' to separate paths from revisions, like this:
39 error git rev-list -n1 indev: 'git <command> [<revision>...] -- [<file>...]'
40 silly trySSH attempting to clone git@github.com:hydrabolt/discord.js.git#indev
41 silly tryClone cloning hydrabolt/discord.js#indev via git@github.com:hydrabolt/discord.js.git#indev
42 verbose tryClone git-github-com-hydrabolt-discord-js-git-indev-3868718b not in flight; caching
43 verbose correctMkdir C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
44 info git [ 'config', '--get', 'remote.origin.url' ]
45 warn addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
45 warn addRemoteGit
45 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
45 warn addRemoteGit     at emitTwo (events.js:106:13)
45 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
45 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
45 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
45 warn addRemoteGit  hydrabolt/discord.js#indev resetting remote C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
45 warn addRemoteGit
45 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
45 warn addRemoteGit     at emitTwo (events.js:106:13)
45 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
45 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
45 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
45 warn addRemoteGit   killed: false,
45 warn addRemoteGit   code: 1,
45 warn addRemoteGit   signal: null,
45 warn addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
46 info resetRemote resetting C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b for hydrabolt/discord.js#indev
47 silly gentlyRm C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b is being purged
48 verbose gentlyRm don't care about contents; nuking C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b
49 silly vacuum-fs purging C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b
50 silly vacuum-fs quitting because other entries in C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes
51 info git [ 'clone',
51 info git   '--template=C:\\Users\\legit\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
51 info git   '--mirror',
51 info git   'git@github.com:hydrabolt/discord.js.git',
51 info git   'C:\\Users\\legit\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-hydrabolt-discord-js-git-indev-3868718b' ]
52 error git clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b: Cloning into bare repository 'C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b'...
52 error git clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b: Permission denied (publickey).
52 error git clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b: fatal: Could not read from remote repository.
52 error git clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b:
52 error git clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b: Please make sure you have the correct access rights
52 error git clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b: and the repository exists.
53 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b
53 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b'...
53 silly fetchPackageMetaData Permission denied (publickey).
53 silly fetchPackageMetaData fatal: Could not read from remote repository.
53 silly fetchPackageMetaData
53 silly fetchPackageMetaData Please make sure you have the correct access rights
53 silly fetchPackageMetaData and the repository exists.
53 silly fetchPackageMetaData
53 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
53 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
53 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
53 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
53 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
53 silly fetchPackageMetaData  error for discord.js@github:hydrabolt/discord.js#indev { Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b
53 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b'...
53 silly fetchPackageMetaData Permission denied (publickey).
53 silly fetchPackageMetaData fatal: Could not read from remote repository.
53 silly fetchPackageMetaData
53 silly fetchPackageMetaData Please make sure you have the correct access rights
53 silly fetchPackageMetaData and the repository exists.
53 silly fetchPackageMetaData
53 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
53 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
53 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
53 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
53 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
53 silly fetchPackageMetaData   killed: false,
53 silly fetchPackageMetaData   code: 128,
53 silly fetchPackageMetaData   signal: null,
53 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true clone --template=C:\\Users\\legit\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\\Users\\legit\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-hydrabolt-discord-js-git-indev-3868718b' }
54 silly rollbackFailedOptional Starting
55 silly rollbackFailedOptional Finishing
56 silly runTopLevelLifecycles Finishing
57 silly install printInstalled
58 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b
58 verbose stack Cloning into bare repository 'C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b'...
58 verbose stack Permission denied (publickey).
58 verbose stack fatal: Could not read from remote repository.
58 verbose stack
58 verbose stack Please make sure you have the correct access rights
58 verbose stack and the repository exists.
58 verbose stack
58 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
58 verbose stack     at emitTwo (events.js:106:13)
58 verbose stack     at ChildProcess.emit (events.js:191:7)
58 verbose stack     at maybeClose (internal/child_process.js:877:16)
58 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
59 verbose cwd C:\Users\legit\Github_Projects\Discord\Bots\DiscordBot-Yappy
60 verbose Windows_NT 10.0.15048
61 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\legit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js"
62 verbose node v6.10.0
63 verbose npm  v4.4.0
64 error code 128
65 error Command failed: git -c core.longpaths=true clone --template=C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:hydrabolt/discord.js.git C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b
65 error Cloning into bare repository 'C:\Users\legit\AppData\Roaming\npm-cache\_git-remotes\git-github-com-hydrabolt-discord-js-git-indev-3868718b'...
65 error Permission denied (publickey).
65 error fatal: Could not read from remote repository.
65 error
65 error Please make sure you have the correct access rights
65 error and the repository exists.
66 verbose exit [ 1, true ]
```

**Comment by Gawdl3y** [comment]
This is a problem with your setup, not with the library. Ask in the [official server](https://discord.gg/bRCvFy9) for further assistance.
