### ISSUE TITLE
Error ID of NULL

### ISSUE THREAD

**Issue by Wolfleader101** [hydrabolt/discord.js#1277]
i get this error:
`E:\DISCORD BOTS\Bot-2\main.js:35
      if (message.member.roles.has(adminRole.id)) {
                                            ^

TypeError: Cannot read property 'id' of null
    at Client.bot.on.message (E:\DISCORD BOTS\Bot-2\main.js:35:45)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (E:\DISCORD BOTS\Bot-2\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (E:\DISCORD BOTS\Bot-2\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (E:\DISCORD BOTS\Bot-2\node_modules\discord.js\src\client\websocket\WebSocketManager.js:273:31)
    at WebSocket.onMessage (E:\DISCORD BOTS\Bot-2\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (E:\DISCORD BOTS\Bot-2\node_modules\ws\lib\WebSocket.js:841:10)`

 **from this code:**

`const Discord = require('discord.js');
const bot = new Discord.Client();

const config = require("./config.json");

bot.on('ready', () => {
  console.log('I am ready!');
});

bot.on('message', message => {
    if(message.author.bot) return;
    if(!message.content.startsWith(config.prefix)) return;

    let command = message.content.split(" ")[0];
    command = command.slice(config.prefix.length);

    let args = message.content.split(" ").slice(1);

    if (command === 'add') {
        let numArray = args.map(n=> parseInt(n));
        let total = numArray.reduce( (p, c) => p+c);
        message.channel.sendMessage(total);
    }

    if (command === 'say') {
        message.channel.sendMessage(args.join(" "));
    }

  if (command === 'ping') {
    message.channel.sendMessage('pong');
  } else

  if (command === 'foo') {
      let adminRole = message.guild.roles.find("names", "Admin");
      if (message.member.roles.has(adminRole.id)) {
          message.channel.sendMessage('bar');
      } else {
          message.reply("***You do not have the permissions to use this command!*** **`You must be `Admin` or above!**");
      }
  }

});
`

**Comment by hydrabolt** [comment]
use `.find"("name")` instead of names, and also null check the adminRole variable first.

Please ask in our discord server for questions such as these, our GitHub repo is for bugs relating the library itself :)
