### ISSUE TITLE
messageReactionAdd Event Error (messageReactionRemove doesn't run at all)

### ISSUE THREAD

**Issue by FireController1847** [hydrabolt/discord.js#1295]
https://github.com/hydrabolt/discord.js/blob/master/src/structures/MessageReaction.js#L34

At the line stated above, it is currently saying "this.emoji" is undefined. messageReactionAdd works fine. 

Full Error:

TypeError: Cannot read property 'name' of undefined
  at new MessageReaction (/root/node_modules/discord.js/src/structures/MessageReaction.js:34:48)
  at Message.patch (/root/node_modules/discord.js/src/structures/Message.js:231:34)
  at MessageUpdateAction.handle (/root/node_modules/discord.js/src/client/actions/MessageUpdate.js:14:17)
  at rest.makeRequest.then.data (/root/node_modules/discord.js/src/client/rest/RESTMethods.js:96:55)
  at propagateAslWrapper (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:421:23)
  at /usr/lib/node_modules/pm2/node_modules/async-listener/index.js:458:70
  at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
`

**Comment by FireController1847** [comment]
Running discord.js@11.0.0  (git://github.com/hydrabolt/discord.js.git#c73b9483f4058f8c8e8ddb6a0bbecfb7a77a449e)

**Comment by FireController1847** [comment]
My mistake, this happens with messageReactionAdd. My messageReactionRemove event does not run on a removement of a reaction, which is a separate issue in itself.

**Comment by FireController1847** [comment]
No-one. Saw. Anything.
