### ISSUE TITLE
Cannot connect to voice

### ISSUE THREAD

**Issue by Yahweasel** [hydrabolt/discord.js#1296]
The bug I'm having with the git version of Discord.js is that I can't connect to voice. The background of why I'm trying the git version:

---

I've been using Discord.js (11.0.0) to receive and record audio streams for a while, and yesterday that stopped working. Exactly as recorded before, my streams confuse libopus in ffmpeg:

```
[libopus @ 0x11de2a0] Decoding error: corrupted stream
Error while decoding stream #0:0: Invalid data found when processing input
```

(That message is repeated over and over)

When I attempt to record a PCM stream instead of an Opus stream (i.e., make the Opus decoding be Discord.js's job), I get a similar error:

```
TypeError: The compressed data passed is corrupted
    at NodeOpusEngine.decode (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/opus/NodeOpusEngine.js:23:25)
    at VoiceReceiver.handlePacket (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/receiver/VoiceReceiver.js:147:59)
    at Socket.VoiceReceiver._listener.msg (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/receiver/VoiceReceiver.js:54:14)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:545:8)
```

---

In the git version, I can't even connect to voice chat at all. I have node-opus, bufferutil, erlpack and sodium installed, have tried with and without uws, and with the Node LTS and Node latest versions.

Regardless, I get the following result:

```
Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/VoiceConnection.js:247:26)
    at connectTimeout.client.setTimeout (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/VoiceConnection.js:268:18)
    at Timeout.setTimeout (/home/yahweasel/craig/node_modules/discord.js/src/client/Client.js:420:7)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

The appearance in Discord itself is that the bot very briefly joins the voice channel, then leaves.

**Comment by iCrawl** [comment]
Please use the [official discord.js Discord server](https://discord.gg/bRCvFy9) for questions; this issue tracker is only intended for bug reports and enhancement suggestions.

**Comment by Yahweasel** [comment]
This is not a question. This is a bug report. The bug is that the latest git of Discord.js cannot connect to voice channels. There were two other bugs as background. There is no question here whatsoever.

**Comment by iCrawl** [comment]
I misread the contents, sorry.

**Comment by iCrawl** [comment]
I redact my statement from before.

Running fine on `c73b9483f4058f8c8e8ddb6a0bbecfb7a77a449e`

**Comment by GregorR** [comment]
Just rechecked, still having the same issue. I'm not sure if I have a slightly different set of packages than I had the last time I checked, but I get a slightly different error:

```
(node:9187) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Tried to send join packet, but the WebSocket is not open.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/yahweasel/craig-eris/node_modules/discord.js/src/client/voice/VoiceConnection.js:247:26)
    at connectTimeout.client.setTimeout (/home/yahweasel/craig-eris/node_modules/discord.js/src/client/voice/VoiceConnection.js:268:18)
    at Timeout.setTimeout (/home/yahweasel/craig-eris/node_modules/discord.js/src/client/Client.js:420:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I don't believe I had that promise rejection before, although I may have just missed it. Still, I get this reliably, and right now the code does nothing more than connect to a specified channel on a specified guild. It doesn't even get as far as creating the receiver.

**Comment by Yahweasel** [comment]
Just rechecked, still having the same issue. I'm not sure if I have a slightly different set of packages than I had the last time I checked, but I get a slightly different error:

```
(node:9187) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Tried to send join packet, but the WebSocket is not open.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/yahweasel/craig-eris/node_modules/discord.js/src/client/voice/VoiceConnection.js:247:26)
    at connectTimeout.client.setTimeout (/home/yahweasel/craig-eris/node_modules/discord.js/src/client/voice/VoiceConnection.js:268:18)
    at Timeout.setTimeout (/home/yahweasel/craig-eris/node_modules/discord.js/src/client/Client.js:420:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I don't believe I had that promise rejection before, although I may have just missed it. Still, I get this reliably, and right now the code does nothing more than connect to a specified channel on a specified guild. It doesn't even get as far as creating the receiver.

(Sorry for the repost, accidental account-hopping)

**Comment by iCrawl** [comment]
I still cannot replicate this? Is this still happening?

Is it on master?

**Comment by Yahweasel** [comment]
Just redid it with master, no bug. I did also use a newer version of Node, so could've been that, or a fixed bug, or a case of the creepin' Yahweasel stupids. Either way, doesn't seem to repeat now. Closed.

**Comment by iCrawl** [comment]
Thanks 👍
