### ISSUE TITLE
Embeds aren't working

### ISSUE THREAD

**Issue by Exgle** [hydrabolt/discord.js#1298]
I'm trying to use embeds on Discord.js using this simple line of code`message.channel.sendEmbed`.
I've been using this for a while now but now it's just stopped working. By stopped working, I mean about 1 hour ago it stopped working.

C:\Users\Sean\Desktop\Bot\Bot.js:23
    message.channel.sendEmbed({
                    ^

`TypeError: message.channel.sendEmbed is not a function
    at Client.client.on.message (C:\Users\Sean\Desktop\Bot\Bot.js:23:21)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at MessageCreateHandler.handle (C:\Users\Sean\Desktop\Bot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Sean\Desktop\Bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:100:65)
    at WebSocketManager.eventMessage (C:\Users\Sean\Desktop\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:225:31)
    at WebSocket.ws.onmessage (C:\Users\Sean\Desktop\Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:83:37)
    at WebSocket.onMessage (C:\Users\Sean\Desktop\Bot\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)`

**Comment by iCrawl** [comment]
Any more info on that? Noone else seems to have that issue.
Can you make sure you run latest master?
`npm i -S hydrabolt/discord.js`

**Comment by Trivaxy** [comment]
I also seem to be having this issue, the difference is that I never used this before and it is not working.

**Comment by Party78** [comment]
i have the same error help pls

**Comment by almostSouji** [comment]
This error is regarding a version of discord.js from 3 years ago, which we do no longer support or maintain. If you experience a bug with the current version (12.4.1) of discord.js please open a new issue and provide all necessary information.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
