### ISSUE TITLE
Range error: Don't use .exists() with IDs. Insteal use .has(id)

### ISSUE THREAD

**Issue by maxerbox** [hydrabolt/discord.js#1319]
Npm version : 4.4.4
Node version: 6.10
Linux ubuntu 16.04

```
 if (prop === 'id') throw new RangeError('Don\'t use .exists() with IDs. Instead, use .has(id).');
                       ^

RangeError: Don't use .exists() with IDs. Instead, use .has(id).
    at Collection.exists (/home/oneprovider/orlybot/node_modules/discord.js/src/util/Collection.js:211:30)
    at Client.bot.on (/home/oneprovider/orlybot/orlybot.js:305:17)
    at emitNone (events.js:91:20)
    at Client.emit (events.js:185:7)
    at WebSocketManager._emitReady (/home/oneprovider/orlybot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:325:17)
    at WebSocketManager.checkIfReady (/home/oneprovider/orlybot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:14)
    at GuildCreateHandler.handle (/home/oneprovider/orlybot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/home/oneprovider/orlybot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/home/oneprovider/orlybot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:273:31)
    at WebSocketClient.internalOnMessage (/home/oneprovider/orlybot/node_modules/uws/uws.js:102:17)
```

**Comment by Drahcirius** [comment]
The error is telling you exactly what is wrong. Use `.has()` instead of `.exists()`
In the future, bring your questions to the official [Discord.js](https://discord.gg/bRCvFy9) server, as the issue tracker is for bugs and enhancements.

**Comment by maxerbox** [comment]
Closed at the same time you answered
