### ISSUE TITLE
Error: Cannot find module "superagent"

### ISSUE THREAD

**Issue by jacbenja** [hydrabolt/discord.js#137]
Im fairly new to js, but i was just trying to run this bot from my computer, and i couldn't seem to not get this error. 

Error: Cannot find module 'superagent'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jacobbenja/Documents/discord.js-master/lib/Client/InternalClient.js:1:874)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

Im on a macbook air running 10.10.5

I have the newest node.js available for mac.
hope someone can help!
Thanks,
   Benja

**Comment by nicholastay** [comment]
`superagent` is a dependency of `discord.js`. It seems like perhaps NPM hasn't installed it properly or you haven't installed the library properly yourself. Maybe try running `npm install discord.js` again to pull deps and the whole library down again?

**Comment by jacbenja** [comment]
ok thanks

**Comment by abalabahaha** [comment]
You should be installing by running `npm install discord.js`, not cloning the git repo.
