### ISSUE TITLE
Sending files returns an error

### ISSUE THREAD

**Issue by SnazzyPine25** [hydrabolt/discord.js#1395]
```js
TypeError: Cannot assign to read only property 'name' of function 'function (){
   return this[Math.floor(Math.random() * ((this.length-1) - 0 + 1)) + 0];
}'
    at TextChannel.send ([redacted]/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:99:23)
    at TextChannel.sendFiles ([redacted]/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:156:17)
    at TextChannel.sendFile ([redacted]/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:168:17)
    at eval (eval at PhotoBox.on ([redacted]/main.js:160:25), <anonymous>:1:21)
    at Client.PhotoBox.on ([redacted]/main.js:160:25)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at MessageCreateHandler.handle ([redacted]/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle ([redacted]/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:123:65)
    at WebSocketManager.eventPacket ([redacted]/node_modules/discord.js/src/client/websocket/WebSocketManager.js:252:31)
    at emitOne (events.js:96:13)
    at WebSocketConnection.emit (events.js:191:7)
    at WebSocketConnection.eventMessage ([redacted]/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:49:12)
    at WebSocket.onMessage ([redacted]/node_modules/ws/lib/EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
```

- discord.js version: 11.1.0
- node.js version: 7.9.0
- Operating system: Ubuntu 16.04 x32
- Priority this issue should have – please be realistic and elaborate if possible: high?

- [x] I have also tested the issue on latest master, commit hash: `a652901d60a7ecb7ce8f77cbb9d1210f049e9e59`

**Comment by 1Computer1** [comment]
Could not replicate, might be a problem on snazzy's end.

**Comment by SnazzyPine25** [comment]
FYI: My code was assigning things to arrays.
```js
Array.prototype.random = function(){
	return this[Math.floor(Math.random() * ((this.length-1) - 0 + 1)) + 0];
}

Array.prototype.pickOff = function(e){
    let a = undefined;
    this.map(i=>{
        if(e.id === i.id){
            a = i;
        }
    });
    return a;
}
```

**Comment by iCrawl** [comment]
This is a really bad shuffle btw.

**Comment by SnazzyPine25** [comment]
Yep.
