### ISSUE TITLE
VoiceChannel Invitation : nullpointer

### ISSUE THREAD

**Issue by kzay** [hydrabolt/discord.js#1495]
When i produce an inviation with and user token. I have an nullpointer exceptions from Invite.setup

```js
        let guild = this.client.guilds.find('name', 'MyGuild'); <= Guild OK
        let voiceChannel = guild.channels.find('name', 'MyVoiceChannel'); <= Channel OK
        let invite = await voiceChannel.createInvite().catch(console.error); <= Crash

TypeError: Cannot read property 'id' of undefined
    at Invite.setup (****\node_modules\discord.js\src\structures\Invite.js:49:51)
    at new Invite (****\node_modules\discord.js\src\structures\Invite.js:40:10)
    at rest.makeRequest.then.invite (****\node_modules\discord.js\src\client\rest\RESTMethods.js:629:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

from the discord.js src

```
/**
     * The guild the invite is for. If this guild is already known, this will be a guild object. If the guild is
     * unknown, this will be a PartialGuild object
     * @type {Guild|PartialGuild}
     */
    this.guild = this.client.guilds.get(data.guild.id) || new PartialGuild(this.client, data.guild);

```

Why returned data.guild is undefined so?

After execute this code, the account is now unverified, i have to validate it again im my mail.

**Further details:**

- discord.js version: lastest
- node.js version: 7.10

**Comment by kzay** [comment]
Information to confirme : "creating an invite link now unverifies you and responds with a 204"

**Comment by devsnek** [comment]
that is true, and i have removed all the methods which will invalidate user accounts in #1490
