### ISSUE TITLE
Discord run error

### ISSUE THREAD

**Issue by NoahLiedFilmSchool** [hydrabolt/discord.js#1553]
Im trying to run my discord.js bot with heroku:

    heroku run bash --app youdonthavetoknow
    Running bash on ⬢ lit-springs-62685... up, run.4786 (Free)
    
Then i type this:

    node .

And its trying to boot the bot but its giving me this error:

    class Util {
    ^^^^^
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:413:25)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/app/node_modules/discord.js/src/index.js:1:76)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)

How to fix this?

**Comment by CyberiumShadow** [comment]
This has nothing to do with discord.js

This is a heroku issue an dusuakly stems from the fact that heroku uses a old version of node which you need to update yourself.

**Comment by NoahLiedFilmSchool** [comment]
Im using the newest version of discord.js

**Comment by NoahLiedFilmSchool** [comment]
how to update?

**Comment by iCrawl** [comment]
You should find help on that issue with the heroku support.
