### ISSUE TITLE
Bot Audit Log Entries Not Returning Anything

### ISSUE THREAD

**Issue by oinkbark** [hydrabolt/discord.js#1586]
**Please describe the problem you are having in as much detail as possible:**
If a bot created an audit log, no properties whatsoever can be pulled from it. If a member created it, the properties work just fine.

**Include a reproducible code sample here, if possible:**
```js
message.guild.fetchAuditLogs({ limit: 1 }).then(logs => logs.entries.first())

/* Full Error:
TypeError: Cannot read property 'id' of undefined
  at new GuildAuditLogsEntry (/discord.js/src/structures/GuildAuditLogs.js:193:56)
  at new GuildAuditLogs (/discord.js/src/structures/GuildAuditLogs.js:55:21)
  at resolve (/discord.js/src/structures/GuildAuditLogs.js:66:20)
  at Promise (<anonymous>)
  at Function.build (/discord.js/src/structures/GuildAuditLogs.js:65:12)
  at rest.makeRequest.then.data (/discord.js/src/client/rest/RESTMethods.js:692:36)
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:208:7)
*/
```

**Further details:**

- discord.js version: 11.1.0 - "12.0.0"
- node.js version: 8.0.0
- Operating system: Mac OSX Sierra
- Priority this issue should have: Low
- [x] I have also tested the issue on latest master, commit hash: #355b1cc
discord.js@12.0.0-dev (git://github.com/hydrabolt/discord.js.git#355b1cca4a527105526ba08b825f95633fc49081)

**Comment by iDroid27210** [comment]
Can confirm this
![confirm](https://user-images.githubusercontent.com/18195429/29455733-9e7ca9f2-8412-11e7-8846-f4d2b086f26e.png)

**Comment by devsnek** [comment]
unable to reproduce @ 9b97fe29
![](https://gc.gy/殮.png)

**Comment by aemino** [comment]
@devsnek Your repro doesn't use limit like their examples do. Perhaps that's related.

**Comment by iCrawl** [comment]
Can this be tested again on master?
