### ISSUE TITLE
unhandled error

### ISSUE THREAD

**Issue by OkitaSougoo** [hydrabolt/discord.js#1625]
**Please describe the problem you are having in as much detail as possible:**
I am not sure if my bot program caused this, but there is an unhandled error which seems to be coming from the library:
```js
Error: Endpoint not provided from voice server packet.
    at VoiceConnection.authenticateFailed (/home/andy/musicbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:256:26)
    at VoiceConnection.setTokenAndEndpoint (/home/andy/musicbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:177:12)
    at ClientVoiceManager.onVoiceServer (/home/andy/musicbot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:28:32)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at VoiceServerUpdate.handle (/home/andy/musicbot/node_modules/discord.js/src/client/websocket/packets/handlers/VoiceServerUpdate.js:15:12)
    at WebSocketPacketManager.handle (/home/andy/musicbot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (/home/andy/musicbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:325:35)
    at WebSocketConnection.onMessage (/home/andy/musicbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:288:17)
    at WebSocket.onMessage (/home/andy/musicbot/node_modules/discord.js/node_modules/ws/lib/EventTarget.js:103:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! musicbot@1.0.0 start: `node --max-old-space-size=2048 src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the musicbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Further details:**

- discord.js version: master
- node.js version: 8.0.0
- Operating system: Linux

- [x] I have also tested the issue on latest master, commit hash: 0a337a4646c2b906a195182bddfcdf4a774fbcbf

**Comment by KyeNormanGill** [comment]
Can you supply some context for us?
Like your code and what line is causing this error?

**Comment by telunc** [comment]
Error stack looks very similar to #1595

**Comment by aemino** [comment]
You forgot to fill out the last part of the issue; the latest commit hash and whether you're using it.

**Comment by OkitaSougoo** [comment]
@aemino i am using the latest for the master branch.

**Comment by hydrabolt** [comment]
Is the issue still occurring?

**Comment by OkitaSougoo** [comment]
I don't think I have this issue anymore. Thanks for the fix.
