### ISSUE TITLE
guild.fetchAuditLogs() returns an Error

### ISSUE THREAD

**Issue by dayxhep** [hydrabolt/discord.js#1626]
When using the fetchAuditLogs function an error occurs:
```
TypeError: Cannot read property 'toLowerCase' of null
    at new GuildAuditLogsEntry (.../node_modules/discord.js/src/structures/GuildAuditLogs.js:226:40)
    at new GuildAuditLogs (.../node_modules/discord.js/src/structures/GuildAuditLogs.js:55:21)
    at resolve (.../node_modules/discord.js/src/structures/GuildAuditLogs.js:66:20)
    at Function.build (.../node_modules/discord.js/src/structures/GuildAuditLogs.js:65:12)
    at rest.makeRequest.then.data (.../node_modules/discord.js/src/client/rest/RESTMethods.js:692:36)
```
```js
var srv = client.guilds.get(Config.server)
if(srv) {
    console.log(srv)
    srv.fetchAuditLogs({limit: 20}).then(al => {
        console.log(al)
    }).catch(throwErr)
}
```
- discord.js version: 11.1.0
- node.js version: v6.9.5
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: Medium

On the last commit on master I have another error:
```
.../node_modules/discord.js/src/errors/Messages.js:84
for (const [name, message] of Object.entries(Messages)) register(name, message);
                                     ^

TypeError: Object.entries is not a function
    at Object.<anonymous> (.../node_modules/discord.js/src/errors/Messages.js:84:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/discord.js/src/errors/index.js:2:27)
    at Module._compile (module.js:570:32)
```

But on git://github.com/hydrabolt/discord.js.git#830d8fb3b510d45e481bb7c9169ef0253bb76a3a
it works perfectly.

**Comment by devsnek** [comment]
on master you will need node 8

**Comment by hydrabolt** [comment]
Does the latest master (ead6d80c36adbeda4a267f7984a69cbfda064106) fix your problem?

**Comment by dayxhep** [comment]
Can not test while the other Error is crashing the bot.
I will open an other for this one and retest it.

**Comment by dayxhep** [comment]
@hydrabolt this commit does the trick :+1:
