### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by dayxhep** [hydrabolt/discord.js#1636]
I do not really know where comes the error,
the stack trace does not show any entry point in my code, maybe a lib version-dependant bug ?
Here is the stack trace:

```
.../node_modules/discord.js/src/errors/Messages.js:84
for (const [name, message] of Object.entries(Messages)) register(name, message);
                                     ^

TypeError: Object.entries is not a function
    at Object.<anonymous> (.../node_modules/discord.js/src/errors/Messages.js:84:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/discord.js/src/errors/index.js:2:27)
    at Module._compile (module.js:570:32)
```

**Further details:**

- discord.js version: discord.js@12.0.0-dev [ead6d80c36adbeda4a267f7984a69cbfda064106](https://github.com/hydrabolt/discord.js/commit/ead6d80c36adbeda4a267f7984a69cbfda064106)
- node.js version: v6.9.5
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by dayxhep** [comment]
Appearing that this issue comes from the node version.
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/entries

**Update Node.js** to latest version does the trick.

**Comment by devsnek** [comment]
for anyone reading this: please pay attention to the package.json because it contains stuff like [this](https://github.com/hydrabolt/discord.js/blob/2a96296e95d39846d40d7ecc0c1b0980928e5238/package.json#L60)

**Comment by VAIBHAV7500** [comment]
I'm still getting this issue.
Node: v10.19.0
Discord: v12.5.1

**Comment by papaia** [comment]
Discord.js v12 requires Node.js v12+.
