### ISSUE TITLE
Bot crashes after a while

### ISSUE THREAD

**Issue by Zimo2** [hydrabolt/discord.js#1642]
Throws this error:

C:\Users\Administrator\Desktop\HaraBot\events\message.js:23
  let everyone = message.guild.roles.get('310148988638593024');
                              ^

TypeError: Cannot read property 'roles' of null
    at Client.module.exports.message (C:\Users\Administrator\Desktop\HaraBot\eve
nts\message.js:23:31)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (C:\Users\Administrator\Desktop\HaraBot\node_
modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Administrator\Desktop\HaraBot\nod
e_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:102:
65)
    at WebSocketConnection.onPacket (C:\Users\Administrator\Desktop\HaraBot\node
_modules\discord.js\src\client\websocket\WebSocketConnection.js:325:35)
    at WebSocketConnection.onMessage (C:\Users\Administrator\Desktop\HaraBot\nod
e_modules\discord.js\src\client\websocket\WebSocketConnection.js:288:17)
    at WebSocket.onMessage (C:\Users\Administrator\Desktop\HaraBot\node_modules\
ws\lib\EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)

**Comment by dragonfire535** [comment]
Trying to use `guild` in a DM perhaps? Should add checks for that.

**Comment by Zimo2** [comment]
Okay

**Comment by aemino** [comment]
It should also be noted that the issue tracker is **not** the place to ask questions about the library. This error is an issue in your code. Please refer to the official Discord.js guild to ask further questions.
