### ISSUE TITLE
AssertionError when fetching members

### ISSUE THREAD

**Issue by dayxhep** [hydrabolt/discord.js#1647]
When starting the bot after a while, i think aproximatively 120s i got this error:
```
AssertionError [ERR_ASSERTION]: An invalid error message key was used: Members didn't arrive in time..
    at message (.../node_modules/discord.js/src/errors/DJSError.js:40:3)
    at DiscordjsError (.../node_modules/discord.js/src/errors/DJSError.js:16:13)
    at client.setTimeout (.../node_modules/discord.js/src/structures/Guild.js:533:16)
    at Timeout.setTimeout [as _onTimeout] (.../node_modules/discord.js/src/client/Client.js:450:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

**Include a reproducible code sample here, if possible:**
```js
global.client   = new Discord.Client({
    fetchAllMembers: true,
})
```

**Further details:**
I think that i get i timeout on the fetchAllMembers in the options but dont really know why

- discord.js version: 12.0.0-dev (git://github.com/hydrabolt/discord.js.git#ead6d80c36adbeda4a267f7984a69cbfda064106)
- node.js version: v8.1.2
- Operating system: Linux
- Priority: low

- [x] I found this issue while running code on a __bot account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by dayxhep** [comment]
Restested on discord.js: lastest, works fine
