### ISSUE TITLE
Assertion Error when using fetchAllMembers = true

### ISSUE THREAD

**Issue by pedall** [hydrabolt/discord.js#1669]
**Please describe the problem you are having in as much detail as possible:**

Error resulting from using the client option `fetchAllMembers: true`

```
 AssertionError [ERR_ASSERTION]: An invalid error message key was used: Members didn't arrive in time..
     at message (/home/pedall-dev/g4m3r/node_modules/komada/node_modules/discord.js/src/errors/DJSError.js:40:3)
     at DiscordjsError (/home/pedall-dev/g4m3r/node_modules/komada/node_modules/discord.js/src/errors/DJSError.js:16:13)
    at client.setTimeout (/home/pedall-dev/g4m3r/node_modules/komada/node_modules/discord.js/src/structures/Guild.js:533:16)
     at Timeout.setTimeout [as _onTimeout] (/home/pedall-dev/g4m3r/node_modules/komada/node_modules/discord.js/src/client/Client.js:450:7)
     at ontimeout (timers.js:488:11)
     at tryOnTimeout (timers.js:323:5)
     at Timer.listOnTimeout (timers.js:283:5)
```

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version: master v12.0.0-dev
- node.js version: 8.1.0
- Operating system: Ubuntu 16.04 (and Mac OS Sierra and High Sierra PB)
- Priority this issue should have – please be realistic and elaborate if possible:
should be high priority since thats a common option to be used and it makes the bots crash / restart
- [ ] I found this issue while running code on a __user account__

- [x] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
This error is fixed in my data store PR, I'll add it into master also.

**Comment by pedall** [comment]
Thank you a lot. Can you tell when it’s in master so I can test if it’s gone? ;)

**Comment by pedall** [comment]
Is there any chance you could give an estimation when this will be merged into the master branch? 

Or is there a specific commit hash I could use in the meantime so that error does not make my bot restart 500 times a day :laughing:

**Comment by devsnek** [comment]
it will be fixed when #1695 is merged

**Comment by pedall** [comment]
i gave it another try, since #1695 is merged into master now.

this is the latest error im getting:

```
[07:10:02] - error: [C 0] Uncaught Exception:
 TypeError: Cannot match against 'undefined' or 'null'.
    at Guild.fetchMembers (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\structures\Guild.js:508:15)
    at promises.client.guilds.map.g (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:141:54)
    at Map.map (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\util\Collection.js:300:47)
    at WebSocketConnection.checkIfReady (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:141:43)
    at GuildCreateHandler.handle (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:331:35)
    at WebSocketConnection.onMessage (C:\Coding\g4m3r\node_modules\komada\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:22)
    at WebSocket.onMessage (C:\Coding\g4m3r\node_modules\komada\node_modules\ws\lib\EventTarget.js:101:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (C:\Coding\g4m3r\node_modules\komada\node_modules\ws\lib\WebSocket.js:146:47)
    at Receiver.dataMessage (C:\Coding\g4m3r\node_modules\komada\node_modules\ws\lib\Receiver.js:380:14)
    at Receiver.getData (C:\Coding\g4m3r\node_modules\komada\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\Coding\g4m3r\node_modules\komada\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\Coding\g4m3r\node_modules\komada\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (C:\Coding\g4m3r\node_modules\komada\node_modules\ws\lib\WebSocket.js:142:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)
```

**Comment by iCrawl** [comment]
@pedall fixed

**Comment by pedall** [comment]
ill retest it later, thanx so much for the fast reaction :-)

**Comment by pedall** [comment]
works now.
