### ISSUE TITLE
"Missing Permmisions" bug

### ISSUE THREAD

**Issue by bloxploits** [hydrabolt/discord.js#1704]
Ok, so i having a problem with a mute command that i created. It says the bot has"Missing Permissions". 
I made a role for the bot, that has all perms ticked, and all perms in each channel ticked.
This error started happening randomly when i used the mute cmd. It was working fine before that, and
I did not change a single bit of the code
I even rewrote the mute cmd, and reinvited my bot into my Discord.

**Include a reproducible code sample here, if possible:**
```js
{ DiscordAPIError: Missing Permissions
    at item.request.gen.end (C:\Users\KalenBulseco\Desktop\Bloxploits bot 2\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:68:65)
    at then (C:\Users\KalenBulseco\Desktop\Bloxploits bot 2\node_modules\snekfetch\src\index.js:242:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'DiscordAPIError',
  message: 'Missing Permissions',
  code: 50013 } Promise {
  <rejected> { DiscordAPIError: Missing Permissions
    at item.request.gen.end (C:\Users\KalenBulseco\Desktop\Bloxploits bot 2\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:68:65)
    at then (C:\Users\KalenBulseco\Desktop\Bloxploits bot 2\node_modules\snekfetch\src\index.js:242:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'DiscordAPIError',
  message: 'Missing Permissions',
  code: 50013 } }
```

**Further details:**

- discord.js version: 1.11.0
- node.js version: 8.2.1
- Operating system: x64

**Comment by Tvde1** [comment]
What command are you trying to execute? You can't for example change the owner's name or kick them.

**Comment by devsnek** [comment]
For issues that aren't library issues, please visit our help server [here](https://discord.gg/bRCvFy9)
