### ISSUE TITLE
`sendFile` fails to send any non-image files specified as URLs

### ISSUE THREAD

**Issue by meew0** [hydrabolt/discord.js#172]
It fails with this error:
```
TypeError: source.on is not a function
    at Function.DelayedStream.create (C:\Users\Khionu\WebstormProjects\DJS_Testing_InDev\node_modules\discord.js\node_modules\superagent\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\lib\delayed_stream.js:33:10)
    at FormData.CombinedStream.append (C:\Users\Khionu\WebstormProjects\DJS_Testing_InDev\node_modules\discord.js\node_modules\superagent\node_modules\form-data\node_modules\combined-stream\lib\combined_stream.js:43:37)
    at FormData.append (C:\Users\Khionu\WebstormProjects\DJS_Testing_InDev\node_modules\discord.js\node_modules\superagent\node_modules\form-data\lib\form_data.js:43:3)
    at Request.attach (C:\Users\Khionu\WebstormProjects\DJS_Testing_InDev\node_modules\discord.js\node_modules\superagent\lib\node\index.js:204:18)
    at InternalClient.apiRequest (C:\Users\Khionu\WebstormProjects\DJS_Testing_InDev\node_modules\discord.js\lib\Client\InternalClient.js:129:8)
    at C:\Users\Khionu\WebstormProjects\DJS_Testing_InDev\node_modules\discord.js\lib\Client\InternalClient.js:592:20
    at process._tickCallback (node.js:368:9)
```

**Comment by GoldenChrysus** [comment]
I also experience this issue. I don't receive any errors. The file simply never gets uploaded by the bot, but images do. Trying to send a MP3 file of size 300 KB.

**Comment by abalabahaha** [comment]
@GoldenChrysus what version of d.js?

**Comment by GoldenChrysus** [comment]
@abalabahaha 6.0.0

**Comment by abalabahaha** [comment]
@GoldenChrysus [faster way of communicating (Discord server)](https://discord.gg/0SBTUU1wZTYd2XyW)
