### ISSUE TITLE
bot.on('voiceLeave') voiceChannel sometimes undefined

### ISSUE THREAD

**Issue by Lord-Ptolemy** [hydrabolt/discord.js#174]
I don't know if this is a library problem or if Discord just doesn't always supply this info, but sometimes when a user leaves the voiceChannel is undefined. I would think it would always supply this data even if they're leaving.

```
C:\Users\Berwyn\Desktop\Discord_Bots\Rosalina_V2\index.js:1762
console.log(lognotice('[' + timestamp + '] ' + 'VOICE LEAVE: ') + user.name + '[' + user.id + '] left voice channel ' + voiceChannel.server.name + '[' + voiceChannel.server.id + ']/' + voiceChannel.name + '[' + voiceChannel.id + ']');

                                        ^

TypeError: Cannot read property 'name' of undefined
    at Client.<anonymous> (C:\Users\Berwyn\Desktop\Discord_Bots\Rosalina_V2\index.js:1762:152)
    at emitTwo (events.js:87:13)
    at Client.emit (events.js:172:7)
    at WebSocket.websocket.onmessage (C:\Users\Berwyn\node_modules\discord.js\lib\Client\InternalClient.js:1723:15)
    at WebSocket.onMessage (C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:816:10)
    at C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\Receiver.js:477:18
    at Receiver.applyExtensions (C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\Receiver.js:364:5)```

**Comment by hydrabolt** [comment]
Are you sure it's not `user` that is undefined? Also, it's `user.username`, not `user.name` ;)

**Comment by meew0** [comment]
There's an alias for that though: https://github.com/hydrabolt/discord.js/blob/master/src/Structures/User.js#L33

**Comment by khionu** [comment]
Meew beat me to it....

**Comment by Lord-Ptolemy** [comment]
``voiceChannel.name`` at the end is what's undefined

**Comment by aequasi** [comment]
Not sure thats possible, because you would get undefined on `voiceChannel.server.name`, and `voiceChannel.server.id` before the first one. Are you sure  `voiceChannel.server` is defined?

**Comment by abalabahaha** [comment]
It appears that the code for voiceLeave returns the server itself if the lib did not cache the user's voice channel.

**Comment by abalabahaha** [comment]
b7c1b6e somewhat resolves this, and maintains basic channel structure if the channel isn't found (passes {server: serverObject} instead of the full channel, do your null checks if necessary :P)
