### ISSUE TITLE
bot.on("messageUpdated") very rarely newMSG.channel.name returns undefined

### ISSUE THREAD

**Issue by Lord-Ptolemy** [hydrabolt/discord.js#175]
Never had this problem on older versions and this is very rare as it's the first time I've had this issue.
``newMSG.channel.name`` returns undefined
**Error**:
```
C:\Users\Berwyn\Desktop\Discord_Bots\Rosalina_V2\index.js:1646
console.log(lognotice('[' + timestamp + '] ' + 'MESSAGE UPDATE: ') + newMSG.channel.server.name + '[' + newMSG.channel.server.id + ']/' + newMSG.channel.name + '[' + newMSG.channel.id + ']/' + newMSG.author.username + '[' + newMSG.author.id  + "] updated message. " + oldMSG.content  + ' --> ' + newMSG.content );
                                                                                              ^

TypeError: Cannot read property 'name' of undefined
    at Client.<anonymous> (C:\Users\Berwyn\Desktop\Discord_Bots\Rosalina_V2\index.js:1646:95)
    at emitTwo (events.js:87:13)
    at Client.emit (events.js:172:7)
    at WebSocket.websocket.onmessage (C:\Users\Berwyn\node_modules\discord.js\lib\Client\InternalClient.js:1404:15)
    at WebSocket.onMessage (C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:816:10)
    at C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\Receiver.js:477:18
    at Receiver.applyExtensions (C:\Users\Berwyn\node_modules\discord.js\node_modules\ws\lib\Receiver.js:364:5)

C:\Users\Berwyn\Desktop\Discord_Bots\Rosalina_V2>
```
**Code**:
```javascript
bot.on('messageUpdated', function(oldMSG, newMSG) {
    console.log(newMSG.channel);
    console.log(lognotice('[' + timestamp + '] ' + 'MESSAGE UPDATE: ') + newMSG.channel.server.name + '[' + newMSG.channel.server.id + ']/' + newMSG.channel.name + '[' + newMSG.channel.id + ']/' + newMSG.author.username + '[' + newMSG.author.id  + "] updated message. " + oldMSG.content  + ' --> ' + newMSG.content );
    if (newMSG.channel.server.id === '42463947818795009' || newMSG.channel.server.id === '97805743893270528' || newMSG.channel.server.id === '102588320181125120') {
        blacklistedWord(newMSG);
    }
});
`

**Comment by abalabahaha** [comment]
Try logging the channel itself.

**Comment by Lord-Ptolemy** [comment]
I've been logging ``newMSG.channel`` and haven't had the issue again as of yet. Will keep logging and see if it appears again. I've also updated my original post to include my code

**Comment by Lord-Ptolemy** [comment]
Closed due to being unable to reproduce issue.
