### ISSUE TITLE
message.guild.voiceConnection.disconnect(); causes crash.

### ISSUE THREAD

**Issue by TheOnlyArtz** [hydrabolt/discord.js#1766]
**Please describe the problem you are having in as much detail as possible:**
```js
C:\Users\win10\Desktop\SpongeBOT\node_modules\discord.js\src\client\voice\VoiceConnection.js:136
    this.sockets.ws.sendPacket({
                   ^

TypeError: Cannot read property 'sendPacket' of null
    at VoiceConnection.setSpeaking (C:\Users\win10\Desktop\SpongeBOT\node_modules\discord.js\src\client\voice\VoiceConnection.js:136:20)
    at StreamDispatcher.dispatcher.on.value (C:\Users\win10\Desktop\SpongeBOT\node_modules\discord.js\src\client\voice\player\AudioPlayer.js:155:61)
    at emitOne (events.js:115:13)
    at StreamDispatcher.emit (events.js:210:7)
    at StreamDispatcher.setSpeaking (C:\Users\win10\Desktop\SpongeBOT\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:117:10)
    at StreamDispatcher.destroy (C:\Users\win10\Desktop\SpongeBOT\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:281:10)
    at StreamDispatcher.process (C:\Users\win10\Desktop\SpongeBOT\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:237:12)
    at Socket.stream.once (C:\Users\win10\Desktop\SpongeBOT\node_modules\discord.js\src\client\voice\dispatcher\StreamDispatcher.js:312:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:502:10)
    at emitReadable (_stream_readable.js:496:7)
    at addChunk (_stream_readable.js:263:7)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
```
This is happening when I'm trying to get my bot disconnect from a voice channel

**Further details:**

- discord.js version: 11.1
- node.js version: 8.12
- Operating system: win 10 pro
- Priority this issue should have – medium (Still lots of music bot using this library)

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Dev-Yukine** [comment]
fixed with #1638 already

**Comment by TheOnlyArtz** [comment]
And I'm still getting it?

**Comment by Dev-Yukine** [comment]
because you use stable and not master .... switch to master or wait until next release

**Comment by iCrawl** [comment]
Also in 11.1-dev
