### ISSUE TITLE
discord.js crashing on update

### ISSUE THREAD

**Issue by moriczgergo** [hydrabolt/discord.js#1797]
**Please describe the problem you are having in as much detail as possible:**
I have been using the latest npm version of discord.js, but since `Playing` statuses don't work anymore, I tried to update to the latest commit on master. It's crashing, and I don't even use voice:

```
/root/claimclaim/node_modules/discord.js/src/structures/VoiceChannel.js:17
    this.members = new Collection();
                 ^

TypeError: Cannot set property members of [object Object] which has only a getter
    at new VoiceChannel (/root/claimclaim/node_modules/discord.js/src/structures/VoiceChannel.js:17:18)
    at Function.create (/root/claimclaim/node_modules/discord.js/src/structures/Channel.js:91:23)
    at ClientDataManager.newChannel (/root/claimclaim/node_modules/discord.js/src/client/ClientDataManager.js:48:29)
    at Guild.setup (/root/claimclaim/node_modules/discord.js/src/structures/Guild.js:187:68)
    at GuildCreateHandler.handle (/root/claimclaim/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/root/claimclaim/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/claimclaim/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:332:35)
    at WebSocketConnection.onMessage (/root/claimclaim/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:294:22)
    at WebSocketClient.internalOnMessage (/root/claimclaim/node_modules/uws/uws.js:103:17)
    at native.client.group.onMessage (/root/claimclaim/node_modules/uws/uws.js:57:15)
```

**Further details:**

- discord.js version: latest from GH master branch (2aa2f73)
- node.js version: v8.4.0
- Operating system: Ubuntu 16.04 LTS
- Priority this issue should have: medium
- Full code: [moriczgergo/claim!claim](https://github.com/moriczgergo/claimclaim)

**Comment by iCrawl** [comment]
#1794 will fix this.

**Comment by moriczgergo** [comment]
@iCrawl Thanks, ETA on when that will be merged?

**Comment by iCrawl** [comment]
Pretty much now :P
