### ISSUE TITLE
Can't rename a voice channel using voiceChannel.setName()

### ISSUE THREAD

**Issue by MaxBly** [hydrabolt/discord.js#1978]
When I try to rename a __voice__ channel, using `voiceChannel.setName('xxx');` or `voiceChannel.edit({name: 'xxx'});` I'm getting this issue:

```js
{ DiscordAPIError: Invalid Form Body
bitrate: int value should be greater than or equal to 8000.
    at DiscordAPIError (/node_modules/discord.js/src/client/rest/DiscordAPIError.js:7:5)
    at item.request.gen.end (/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/node_modules/snekfetch/src/index.js:200:21)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  name: 'DiscordAPIError',
  message: 'Invalid Form Body\nbitrate: int value should be greater than or equal to 8000.',
  path: '/api/v7/channels/267753901275611136',
  code: 50035 }
```
It works perfectly while renaming a __text__ channel, this happen only while renaming a __voice__ channel. I've asked the discord server, we didn't solve this issue. :/

**Further details:**

- discord.js version: 11.2.1
- node.js version: 6.5.0
- Operating system: Raspbian

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Dev-Yukine** [comment]
this error is already fixed on master so you could wait until release and try not using it or you update to master to get a fix (but there are breaking changes where you need to rewrite your code)

**Comment by Dev-Yukine** [comment]
also you could use the commit from #1955 if you need a workaround now

**Comment by MaxBly** [comment]
I just updated to the master branch and I got this issue

```js
const AllowedImageSizes = Array.from({ length: 8 }, (e, i) => 2 ** (i + 4));
                                                                 ^
SyntaxError: Unexpected token *
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/prgm/discord/blybot/node_modules/discord.js/src/util/Util.js:3:47)
    at Module._compile (module.js:556:32)

```

**Comment by MaxBly** [comment]
I've deleted the `*` and this happen:
```js
/prgm/discord/blybot/node_modules/discord.js/src/errors/Messages.js:97
for (const [name, message] of Object.entries(Messages)) register(name, message);
                                     ^

TypeError: Object.entries is not a function
    at Object.<anonymous> (/prgm/discord/blybot/node_modules/discord.js/src/errors/Messages.js:97:38)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/prgm/discord/blybot/node_modules/discord.js/src/errors/index.js:2:27)
    at Module._compile (module.js:556:32)
 ```

**Comment by devsnek** [comment]
you need to update to the latest version of node.js

**Comment by MaxBly** [comment]
ok thx ofc it works very well now! your my hero <3

**Comment by Catishere** [comment]
It is not fixed

**Comment by almostSouji** [comment]
Since the proposed code does not produce any errors on version 12.3.1 (latest stable at the time of writing this) and does otherwise not produce any unexpected behavior: yes, the issue is fixed.

```js
const c = message.guild.channels.resolve('585382668842041375');
await c.setName('xxx');
await c.edit({ name: 'yyy' });
```

![image](https://user-images.githubusercontent.com/26532370/93654630-d784f800-fa1e-11ea-950d-0c84ff3f8a91.png)

If your command was caused by the channel simply not updating please keep in mind that discord has recently majorly increased the rate limit on channel name and topic updates to about 2 edits per 10 minutes.
