### ISSUE TITLE
Cannot read property 'equals' of null

### ISSUE THREAD

**Issue by ZR2** [hydrabolt/discord.js#200]
```
info: Executing <!purge 1> from Josh (ZR2)
/home/divbot/node_modules/discord.js/lib/Structures/ServerChannel.js:53
                        if (this.server.owner.equals(user)) {
                                             ^
TypeError: Cannot read property 'equals' of null
    at TextChannel.permissionsOf (/home/divbot/node_modules/discord.js/lib/Structures/ServerChannel.js:53:25)
    at Object.Commands.purge.fn (/home/divbot/runtime/commands.js:381:22)
    at /home/divbot/DougBot.js:193:33
    at Object.exports.GetLevel (/home/divbot/runtime/permissions.js:9:12)
    at Client.<anonymous> (/home/divbot/DougBot.js:174:21)
    at Client.emit (events.js:107:17)
    at WebSocket.websocket.onmessage (/home/divbot/node_modules/discord.js/lib/Client/InternalClient.js:1365:16)
    at WebSocket.onMessage (/home/divbot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/home/divbot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:816:10)
```

**Comment by abalabahaha** [comment]
Server owner is offline and large threshold is trolling so hard...

_~~Better~~WorserDiscord pls_

Try latest indev.

**Comment by ZR2** [comment]
Yeah it works thanks for that
