### ISSUE TITLE
TypeError: Cannot read property "roles" of null

### ISSUE THREAD

**Issue by WinWowsTM** [hydrabolt/discord.js#2033]
Hello, I'm somewhat experienced with discord.js, I'm trying to code a moderation bot. However, there is an error that has been bugging me for a long time, that I can't seem to figure out is a null error. Please ignore about the fact i'm using TextChannel#sendMessage, i just prefer it, so here is my code:

`` case "promote":
          let promotestaffRole = message.guild.roles.find("name", "Admins");
          if(message.member.roles.has(promotestaffRole.id)) {
            let promoteUser = message.mentions.users.first();
            let promoteModRole = message.guild.roles.find("name", "Mods");
            if(!message.mentions.users.size < 1) return message.reply(":x: ERROR: Incorrect usage. Use: ```!promote <.user>").catch(console.error);
            if (message.guild.member(promoteUser).roles.has(promoteModRole.id)) {
              message.channel.sendMessage(":x: ERROR: This user already has been promoted. To demote, use: ```!demote <.user>```");
              return;
            } else {
              message.guild.member(promoteUser).addRole(promoteModRole);
              message.channel.sendMessage(`:white_check_mark: SUCCESS: Successfully promoted **${promoteUser.tag}**.`);
              promoteUser.sendMessage(`:information_source: INFO: You have been **promoted** on ${message.guild.name}! Congrats! :clap: :clap:`);
              client.channels.find("name", "announcements").sendMessage(`${promoteUser.tag} has been **promoted**! Wowee! Congrats ${promoteUser.tag}! :D`);
              return;
            }
          } else {
            message.reply(":x: ERROR: You do not have sufficient access to use that command. Required role: Admins");
            return;
          }
          break;``

Here is the error:
if (message.guild.member(promoteUser).roles.has(promoteModRole.id)) {
                                                 ^

TypeError: Cannot read property 'roles' of null
    at Client.<anonymous> (C:\Users\WinWowsTM\Documents\Bot!\index.js:454:50)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (C:\Users\WinWowsTM\Documents\Bot!\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCrea
te.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\WinWowsTM\Documents\Bot!\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketMan
ager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\WinWowsTM\Documents\Bot!\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:
35)
    at WebSocketConnection.onMessage (C:\Users\WinWowsTM\Documents\Bot!\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293
:17)
    at WebSocket.onMessage (C:\Users\WinWowsTM\Documents\Bot!\node_modules\ws\lib\EventTarget.js:99:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)

This error is so annoying. Please help me?

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
