### ISSUE TITLE
discord.js/src/util Syntax Error, not yet supported outside of strict mode

### ISSUE THREAD

**Issue by OverloadedCore** [hydrabolt/discord.js#2049]
I have just tried to create my first discord bot. I have used npm to install discord.js and the code for my bot is as follows:
```
const Discord = require("discord.js");
const bot = Discord.Client();

bot.login("[BLOCKED]"); 
```
But when I run it with `nodejs .` it comes up with the following error:
```
[BLOCKED]/node_modules/discord.js/src/util/Util.js:8
class Util {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/overloadedcore/Documents/discord bots/CoreBot/node_modules/discord.js/src/index.js:1:76)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

Extra notes:

- OS: Ubuntu 16.04 LTS

**Comment by SpaceEEC** [comment]
This error means that you don't have node 6 or newer running.
Since you are using Ubuntu, something like `n` or `nvm`, makes it pretty trivial to update.

**Comment by OverloadedCore** [comment]
Thank you to @SpaceEEC For telling me this, I went to the website and downloaded node.js directly from there, took the file out of the bin directory, and ran it using that `./node .`
That fixed it, thank you once again

**Comment by Gawdl3y** [comment]
@OverloadedCore Just use [the Nodesource repo](https://github.com/nodesource/distributions).
