### ISSUE TITLE
issues with shard communication master <> children

### ISSUE THREAD

**Issue by pedall** [hydrabolt/discord.js#2102]
**Please describe the problem you are having in as much detail as possible:**

changed no code, only updated discord.js to latest master version. Shown code snippet worked for the last 5 month with no error.

```js
Error [SHARDING_PARENT_CONNECTION]: Error when sending eval response to master process: Failed to send message to master process.
(node:20176) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Failed to send message to shard's process.
```

respective error to the one before
```js
[23:27:40] - error: [Shard 0]  Error [SHARDING_PARENT_CONNECTION]: Failed to send message to master process.
    at Promise (/mnt/home/pedall-beta/g4m3r/node_modules/discord.js/src/sharding/ShardClientUtil.js:45:24)
    at new Promise (<anonymous>)
    at ShardClientUtil.send (/mnt/home/pedall-beta/g4m3r/node_modules/discord.js/src/sharding/ShardClientUtil.js:41:12)
    at Promise (/mnt/home/pedall-beta/g4m3r/node_modules/discord.js/src/sharding/ShardClientUtil.js:90:12)
    at new Promise (<anonymous>)
    at ShardClientUtil.broadcastEval (/mnt/home/pedall-beta/g4m3r/node_modules/discord.js/src/sharding/ShardClientUtil.js:82:12)
    at module.exports.run (/mnt/home/pedall-beta/g4m3r/monitors/memberActivity.js:40:37)
    at <anonymous>
```

**Include a reproducible code sample here, if possible:**
```js
if (bot.userCache.has(user.id)) {
  await this.client.shard.broadcastEval(`
    const user = bot.userCache.get("${user.id}");
    user.messages = user.messages + 1;
  `).catch(e => logger.error(e));
}
```

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: 8.9.1
- Operating system: Ubuntu 16.01 and macOS 10.12.6
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 62544905a06152ca769c4e6d5f16337b134ac67e

**Comment by pedall** [comment]
I do not know what was causing this but it is gone now. (hopefully only some local hickups of my machine)
