### ISSUE TITLE
ffmpeg Error: spawn EACCES

### ISSUE THREAD

**Issue by PlayBy** [hydrabolt/discord.js#2154]
Somebody help me please. Running my bot on my laptop works fine, music plays. Running it on my Raspberry PI (What I host my bot off of) has an error. 

`{ Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:499:9)
    at new FfmpegProcess (/home/pi/Desktop/Discord Bot/node_modules/prism-media/src/transcoders/ffmpeg/FfmpegProcess.js:14:33)
    at FfmpegTranscoder.transcode (/home/pi/Desktop/Discord Bot/node_modules/prism-media/src/transcoders/ffmpeg/Ffmpeg.js:34:18)
    at MediaTranscoder.transcode (/home/pi/Desktop/Discord Bot/node_modules/prism-media/src/transcoders/MediaTranscoder.js:27:31)
    at Prism.transcode (/home/pi/Desktop/Discord Bot/node_modules/prism-media/src/Prism.js:13:28)
    at AudioPlayer.playUnknownStream (/home/pi/Desktop/Discord Bot/node_modules/discord.js/src/client/voice/player/AudioPlayer.js:97:35)
    at VoiceConnection.playStream (/home/pi/Desktop/Discord Bot/node_modules/discord.js/src/client/voice/VoiceConnection.js:483:24)
    at message.member.voiceChannel.join.then.connection (/home/pi/Desktop/Discord Bot/bot.js:574:47) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
`

I have no clue why this is happening and I need help fast..

**Comment by Dev-Yukine** [comment]
if you would have googled `Error: spawn EACCES` you would have known that this issue is related to your process has not enough permissions to spawn an FFMPEG process also if you really want fast help next time ask in our [Official Discord Server](https://discordapp.com/invite/bRCvFy9) 🤔

**Comment by PlayBy** [comment]
What do you think I did not google it? OF COURSE ITS A PROBLEM WITH FFMPEG! Now how in the hell do I fix it?

**Comment by BigBrainAFK** [comment]
Last time i checked this is discord.js support not ffmpeg support.

**Comment by Dev-Yukine** [comment]
by reading my comment. i already told you that your process is missing permission to create a fmmpeg process and that issue is with which permission you start your node process and not related to discord.js
