### ISSUE TITLE
<User>.send() throws error even tho the message was sent successfully

### ISSUE THREAD

**Issue by CheesyZaem** [hydrabolt/discord.js#2174]
**Please describe the problem you are having in as much detail as possible:**
While using <User>.send(), it throws an error, and here is the error:

TypeError: Cannot read property 'id' of null
    at Client.bot.on.msg (/root/bot/bot.js:125:37)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateAction.handle (/root/bot/node_modules/discord.js/src/client/actions/MessageCreate.js:25:14)
    at channel.client.api.channels.(anonymous function).messages.post.then.d (/root/bot/node_modules/discord.js/src/structures/shared/SendMessage.js:22:53)
    at \<anonymous\>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Include a reproducible code sample here, if possible:**
```js
<User>.send("something").catch((err) => console.log(err.stack));
```

**Further details:**

- discord.js version: master
- node.js version: 8.9.1
- Operating system: Ubuntu

**Comment by SpaceEEC** [comment]
`at Client.bot.on.msg (/root/bot/bot.js:125:37)`
Looks like the error is being thrown in your bot.js at line 125.

**Comment by CheesyZaem** [comment]
I did it through eval, so that's where my eval command located.

**Comment by Lewdcario** [comment]
Cannot reproduce on latest master branch.

**Comment by HorizonTM** [comment]
Same here.

**Comment by CheesyZaem** [comment]
Sorry, it's my own mistake.
