### ISSUE TITLE
Unhandled promise rejection during for HTTP 5XX

### ISSUE THREAD

**Issue by Freemanium** [hydrabolt/discord.js#2223]
During a high workload of Discord's API (response time >= 1000ms), discord.js dropped an unhandled promise rejection. It was too short to debug where it happened in my code, but it was during setup, within the `client.on('ready')` handler.
```
TypeError: Cannot read property 'options' of undefined
  at item.request.gen.end ($$$\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:69:75)
  at then ($$$\node_modules\snekfetch\src\index.js:218:21)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:188:7)
```
The excerpt from Sequential.js (lines 67-70)
```js
} else if (err.status >= 500 && err.status < 600) {
  this.queue.unshift(item);
  this.restManager.client.setTimeout(resolve, 1e3 + this.client.options.restTimeOffset);
}                                                               ^^^^^^^
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 9.2.1
- Operating system: Windows 10 x64
- Priority this issue should have: low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Freemanium** [comment]
Already resolved #2189
