### ISSUE TITLE
Collection: this.iter is not a function

### ISSUE THREAD

**Issue by EllenFawkes** [hydrabolt/discord.js#2236]
I created my collection, sorted it and called `.firstKey(10)` and I got error:

```javascript
/opt/PurrplingBot/node_modules/discord.js/src/util/Collection.js:88
    const iter = this.iter();
                      ^

TypeError: this.iter is not a function
    at Map.firstKey (/opt/PurrplingBot/node_modules/discord.js/src/util/Collection.js:88:23)
    at Timeout.hallOfFame [as _onTimeout] (/opt/PurrplingBot/plugins/Wordcounter/wordcounter.js:105:14)
    at ontimeout (timers.js:476:15)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

```javascript
function hallOfFame(message, type, top = 10) {
  if (!message.guild) return;
  logger.info("Processing hall of fame - %s ...", type);
  var guildID = message.guild.id;
  var guildStats = counterStore[guildID];

  const discordjs = require("discord.js");
  const Collection = discordjs.Collection;
  var fame = new Collection();

  for (userID in guildStats) {
    fame.set(userID, guildStats[userID][type]);
  }

  // Sort hall of fame board from the biggest score to lowest (DESCENDING)
  var sortedFame = fame.sort(function(a, b){return b-a});

  var msg = "Hall of fame - " + type + "\n\n";
  var no = 1;
  sortedFame.firstKey(10).forEach(function(userID){
    var client = PurrplingBot.getDiscordClient();
    var user = client.users.find('id', userID);
    var score = sortedFame.get(userID)
    if (!user) user = {username: "deleted-user"};
    msg += no + ". " + user.username + " - " + score + " " + type + "\n";
    no++;
  });

  message.channel.send(msg).then(logger.info("Sent hall of fame to #% requested by: %s", message.channel.name, message.author.username));
  message.channel.stopTyping();
}
```

**Further details:**

- discord.js version: 11.2.0
- node.js version: 8.5.0
- Operating system: Linux (Docker)
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by EllenFawkes** [comment]
I found fix in `master` https://github.com/hydrabolt/discord.js/pull/1889/files#diff-d956a9670343f71a391c8ab89ae051b5R88

In 11.3.-dev it's not fixed
https://github.com/hydrabolt/discord.js/blob/d94ead70f82b65e5a12b685efe8acae82500f25e/src/util/Collection.js#L88

@hydrabolt @Gawdl3y  Do you cherry-pick it to `11.3.0` or `11.2.2`?
