### ISSUE TITLE
Error when creating channel in category

### ISSUE THREAD

**Issue by DanielOhanessian** [hydrabolt/discord.js#2239]
**Please describe the problem you are having in as much detail as possible:**
I am trying to create a channel inside of a category, but when I do, I get an error that `channelType.toUpperCase is not a function`.

**Include a reproducible code sample here, if possible:**
```js
var name = "Hello World!";
var channelname = name.replace(/\W/g, '').toLowerCase();
var category = message.guild.channels.get("[channel id]");
message.guild.createChannel(channelname, {parent: category});
```

**Further details:**

Full error:
```
TypeError: channelType.toUpperCase is not a function
    at RESTMethods.createChannel (/root/node_modules/discord.js/src/client/rest/RESTMethods.js:282:62)
    at Guild.createChannel (/root/node_modules/discord.js/src/structures/Guild.js:908:37)
    at Object.func (/root/Onessia-Bot/bot.js:570:25)
    at Client.client.on.msg (/root/Onessia-Bot/bot.js:603:19)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (/root/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/root/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
```

- discord.js version: v11.3-dev
- node.js version: v6.11.5
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Mild

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: I used `npm i hydrabolt/discord.js#11.3-dev`

**Comment by Lewdcario** [comment]
If you looked at the docs for 11.3-dev we don't take an object at all anywhere in the method.
![image](https://user-images.githubusercontent.com/11844002/34741377-16472c5e-f548-11e7-8711-10623e29ae09.png)

**Comment by DanielOhanessian** [comment]
OK, but how would you set a parent to a channel in 11.3-dev then?

**Comment by devsnek** [comment]
you don't, 11.3 has no support for it

**Comment by DanielOhanessian** [comment]
Oh ok, makes sense.

**Comment by Lewdcario** [comment]
Read the documentation to find your answers instead of making an issue.

**Comment by DanielOhanessian** [comment]
Yeah, sorry about that, I just got confused about what's the difference between master and 11.3-dev, and I did ask this on the Discord chat, but no one really responded.
