### ISSUE TITLE
Todays update has made it so bots can't login

### ISSUE THREAD

**Issue by AlexTrott** [hydrabolt/discord.js#24]
Hey, so my bot was working fine, and since the update to discord this morning, my bot is unable to login. I get the following issue : 

```
Alexs-iMac:Kanye-Bot alextrott$  node index.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

Is there a quick fix for this?

**Comment by AlexTrott** [comment]
discord fixed the issue
