### ISSUE TITLE
Kicking a bot account from the server crashes the bot

### ISSUE THREAD

**Issue by ZudoMC** [hydrabolt/discord.js#267]
/root/pigbot/node_modules/discord.js/lib/Client/InternalClient.js:1548
                                                                if (!self.servers.find(function (s) {
                                                                                  ^
    TypeError: undefined is not a function
    at WebSocket.websocket.onmessage (/root/pigbot/node_modules/discord.js/lib/Client/InternalClient.js:1548:27)
    at WebSocket.onMessage (/root/pigbot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/root/pigbot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:816:10)
    at /root/pigbot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/root/pigbot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:364:5)
    at /root/pigbot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (/root/pigbot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.opcodes.1.finish (/root/pigbot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:482:12)
    at Receiver.expectHandler (/root/pigbot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:457:31)

On a kick, the bot crashes.

**Comment by abalabahaha** [comment]
This has been fixed in development, but not in a release yet. Upgrading to NodeJS 4.0.0 or later will fix this, otherwise you would have to wait for next release
