### ISSUE TITLE
Random crash: TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by brussell98** [hydrabolt/discord.js#271]
Stack:
```
TypeError: Cannot read property 'id' of null
     at WebSocket.websocket.onmessage (/home/bruss/bot-chan/node_modules/discord.js/lib/Client/InternalClient.js:2116:14)
     at WebSocket.onMessage (/home/bruss/bot-chan/node_modules/ws/lib/WebSocket.js:442:14)
     at emitTwo (events.js:100:13)
     at WebSocket.emit (events.js:185:7)
     at Receiver.ontext (/home/bruss/bot-chan/node_modules/ws/lib/WebSocket.js:841:10)
     at /home/bruss/bot-chan/node_modules/ws/lib/Receiver.js:536:18
     at Receiver.applyExtensions (/home/bruss/bot-chan/node_modules/ws/lib/Receiver.js:371:5)
     at /home/bruss/bot-chan/node_modules/ws/lib/Receiver.js:508:14
     at Receiver.flush (/home/bruss/bot-chan/node_modules/ws/lib/Receiver.js:347:3)
     at Receiver.opcodes.1.finish (/home/bruss/bot-chan/node_modules/ws/lib/Receiver.js:541:12)
```
pls fix it's annoying

**Comment by abalabahaha** [comment]
As discussed in Discord, probably a undefined check for `user`

**Comment by brussell98** [comment]
After adding a check for `user` at the if statement on line 2116 this hasn't occurred again

**Comment by abalabahaha** [comment]
In indev now

**Comment by OmegabyteStudios** [comment]
Same thing happening to me!

**Comment by KingDGrizzle** [comment]
@OmegabyteStudios, sorry to be the one hitting the barrel, but you literally commented on an almost 2 year old issue. If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
