### ISSUE TITLE
Heroku bot.joinVoiceChannel

### ISSUE THREAD

**Issue by Milhound** [hydrabolt/discord.js#285]
The following code works locally, but will cause a crash on Heroku. Specifically the bot.joinVoiceChannel command. It is important to note, the bot does actually join the correct voice channel.

```js
function play(msg) {
    if(!playing){
        if (queue.length > 0 && !playing) {
            var song = getNextSong();
            var channel = msg.sender.voiceChannel;
            bot.joinVoiceChannel(channel, (error, conn) => {
                    if (error){
                        throw error;
                    }
                    console.log('Bot Joined Voice Channel');
                    playSong(conn, song);
            });
        }
    }
}
```

Output:
```
removed temporary voice websocket listeners
2016-04-18T19:14:34.140951+00:00 app[worker.1]: events.js:154
2016-04-18T19:14:34.140971+00:00 app[worker.1]:       throw er; // Unhandled 'error' event
2016-04-18T19:14:34.140972+00:00 app[worker.1]:       ^
2016-04-18T19:14:34.140973+00:00 app[worker.1]: 
2016-04-18T19:14:34.140974+00:00 app[worker.1]: Error: read ECONNRESET
2016-04-18T19:14:34.140975+00:00 app[worker.1]:     at exports._errnoException (util.js:890:11)
2016-04-18T19:14:34.140975+00:00 app[worker.1]:     at TLSWrap.onread (net.js:552:26)
```

**Comment by Milhound** [comment]
Issue not resolved, but discovered. Heroku does not allow for UDP traffic, only HTTP.

**Comment by meew0** [comment]
If that's the issue, then you're out of luck because Discord only allows voice traffic over UDP.
