### ISSUE TITLE
Crash when unblocking bot with OAuth bot account

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#321]
http://pastebin.com/ifnm4RFQ

Requires verification but this is what I believe happneed.

**Comment by abalabahaha** [comment]
You aren't supposed to be able to have friends as a bot...

**Comment by macdja38** [comment]
yea... Idk if it was actually someone denying it's friendship or sending then removing a friend request. because I only accepted like 3 people as pvpcraft's friend's and I don't think any of them would have unfriended it.

**Comment by macdja38** [comment]
ahh, I see @abalabahaha I think this happened when it was unblocked by someone. at least, this is what happens when I unblock it.
```
pvpcraft-9 TypeError: Cannot read property 'get' of null
pvpcraft-9     at WebSocket.websocket.onmessage (/Bots/pvpcraft/node_modules/discord.js/lib/Client/InternalClient.js:2325:29)
pvpcraft-9     at WebSocket.onMessage (/Bots/pvpcraft/node_modules/ws/lib/WebSocket.js:442:14)
pvpcraft-9     at emitTwo (events.js:100:13)
pvpcraft-9     at WebSocket.emit (events.js:185:7)
pvpcraft-9     at Receiver.ontext (/Bots/pvpcraft/node_modules/ws/lib/WebSocket.js:841:10)
pvpcraft-9     at /Bots/pvpcraft/node_modules/ws/lib/Receiver.js:536:18
pvpcraft-9     at Receiver.applyExtensions (/Bots/pvpcraft/node_modules/ws/lib/Receiver.js:371:5)
pvpcraft-9     at /Bots/pvpcraft/node_modules/ws/lib/Receiver.js:508:14
pvpcraft-9     at Receiver.flush (/Bots/pvpcraft/node_modules/ws/lib/Receiver.js:347:3)
pvpcraft-9     at Receiver.opcodes.1.finish (/Bots/pvpcraft/node_modules/ws/lib/Receiver.js:541:12)
```
