### ISSUE TITLE
TypeError: Cannot read property 'permissions' of null

### ISSUE THREAD

**Issue by Lord-Ptolemy** [hydrabolt/discord.js#325]
**Code:**
```javascipt
 if (!message.channel.isPrivate && message.author.id !== bot.user.id && gbans.indexOf(message.author.id) === -1 && globalIgnore.ignored.indexOf(message.author.id) === -1) {
    var bot_permissions = message.channel.permissionsOf(bot.user.id); // Where it errors
    var bot_can_invite = bot_permissions.hasPermission("createInstantInvite");
```

**Console:**
```javascript
[5-May,09:59:32PM, EST-0400] VOICE JOIN: Maciel[83633862697050112] joined voice channel Team Xenocide[81137194554621952]/Team Xenocide[81138758518312960]
[5-May,09:59:32PM, EST-0400] SERVER CREATED: Team Xenocide[81137194554621952]
[5-May,09:59:32PM, EST-0400] SERVER MEMBER UPDATED: Team Xenocide[81137194554621952]Cherry Blossoms[131607467669979136]
[5-May,09:59:32PM, EST-0400] SERVER ROLE CREATED: Cherry Blossoms
{ serverinfo:
   { '97805743893270528': { whitelist: [Object] },
     '102588320181125120': { whitelist: [] },
     '103028520011190272': { whitelist: [Object] },
     '132246326657286144': { whitelist: [] },
     '95657260969103360': { whitelist: [Object] },
     '112735322504232960': { whitelist: [] },
     '135076441460178944': { whitelist: [] },
     '110373943822540800': { whitelist: [Object] },
     '88402934194257920': { whitelist: [] },
     '107116254896087040': { whitelist: [] },
     '114936662684991493': { whitelist: [] },
     '77710284621357056': { whitelist: [Object] },
     '124708927530205184': { whitelist: [Object] },
     '105010597954871296': { whitelist: [] },
     '135997489546395648': { whitelist: [] },
     '108580167516991488': { whitelist: [] },
     '81384788765712384': { whitelist: [Object] },
     '91087052312940544': { whitelist: [] },
     '42463947818795009': { whitelist: [Object] },
     '96718795594268672': { whitelist: [] },
     '115609972250902530': { whitelist: [] },
     '152695325637738496': { whitelist: [Object] },
     '140646775047323649': { whitelist: [] },
     '160201156268785664': { whitelist: [] },
     '142745858667053057': { whitelist: [Object] },
     '171951546488061953': { whitelist: [] },
     '102559432646365184': { whitelist: [] },
     '177075981847232513': { whitelist: [] },
     '170580784862855168': { whitelist: [] },
     '96554311349190656': { whitelist: [] },
     '177156103761690624': { whitelist: [] },
     '146004974793392130': { whitelist: [Object] },
     '112001361045897216': { whitelist: [] },
     '177067106146320385': { whitelist: [] },
     '176349920725303297': { whitelist: [] },
     '177427610479886338': { whitelist: [] },
     '157986014747426817': { whitelist: [] },
     '176557388566888448': { whitelist: [Object] },
     '177625690546372608': { whitelist: [] },
     '116284381932290050': { whitelist: [] },
     '177641164143460352': { whitelist: [] },
     '105353529253715968': { whitelist: [] },
     '148298133233729536': { whitelist: [] },
     '177275824150544384': { whitelist: [] },
     '81137194554621952': { whitelist: [] } } }
null
[5-May,09:59:32PM, EST-0400] VOICE LEAVE: Minecraft Dude PGMB[126125105712463872] left voice channel Discord API[81384788765712384]/Development[131937951394430976]
[5-May,10:0:12PM, EST-0400] SERVER MEMBER UPDATED: PC MASTER RACE[77710284621357056]Tyler 4 Hayley �[95721497905074176]
null
[5-May,10:0:14PM, EST-0400] VOICE LEAVE: ༺ʌρ๏�⚜ᗷØŁŦ༻[167755413918449664] left voice channel #BooBot Hangout[105010597954871296]/afk plebs � �[136392354503327744]
[5-May,10:0:27PM, EST-0400] SERVER NEW MEMBER: SamstepPlayz[136637808063414272] joined Technic[42463947818795009]
C:\Discord_Bots\Rosalina_Bottings_V2\node_modules\discord.js\lib\Structures\ServerChannel.js:91
                                permissions |= serverRole.permissions;
                                                         ^

TypeError: Cannot read property 'permissions' of null
    at TextChannel.permissionsOf (C:\Discord_Bots\Rosalina_Bottings_V2\node_modules\discord.js\lib\Structures\ServerChannel.js:91:30)
    at Client.<anonymous> (C:\Discord_Bots\Rosalina_Bottings_V2\index.js:1110:43)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (C:\Discord_Bots\Rosalina_Bottings_V2\node_modules\discord.js\lib\Client\InternalClient.js:1752:16)
    at WebSocket.onMessage (C:\Discord_Bots\Rosalina_Bottings_V2\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:92:20)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Discord_Bots\Rosalina_Bottings_V2\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\Discord_Bots\Rosalina_Bottings_V2\node_modules\discord.js\node_modules\ws\lib\Receiver.js:536:18

C:\Discord_Bots\Rosalina_Bottings_V2>
```
Probably related to issue #324

**Comment by abalabahaha** [comment]
Hopefully fixed by af333ef
