### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by briantanner** [hydrabolt/discord.js#331]
On indev, SERVER_MEMBER_REMOVE triggered

```
/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/lib/Util/Cache.js:137
			if (this[i][this[discrimS]] === data[this[discrimS]]) {
			           ^

TypeError: Cannot read property 'id' of undefined
    at Cache.remove (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/lib/Util/Cache.js:137:15)
    at WebSocket.websocket.onmessage (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/lib/Client/InternalClient.js:2054:23)
    at WebSocket.onMessage (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.ontext (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/Users/briantanner/GitRepos/Grepolis-DiscordBot/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
```

**Comment by OmegabyteStudios** [comment]
I am having the same problem!
