### ISSUE TITLE
TypeError: Cannot read property 'get' of null

### ISSUE THREAD

**Issue by brussell98** [hydrabolt/discord.js#343]
TypeError: Cannot read property 'get' of null
       at WebSocket.websocket.onmessage (/home/brussell/bot-chan/node_modules/discord.js/lib/Client/InternalClient.js:2351:29)
       at WebSocket.onMessage (/home/brussell/bot-chan/node_modules/ws/lib/WebSocket.js:442:14)
       at emitTwo (events.js:106:13)
       at WebSocket.emit (events.js:191:7)
       at Receiver.ontext (/home/brussell/bot-chan/node_modules/ws/lib/WebSocket.js:841:10)
       at /home/brussell/bot-chan/node_modules/ws/lib/Receiver.js:536:18
       at Receiver.applyExtensions (/home/brussell/bot-chan/node_modules/ws/lib/Receiver.js:371:5)
       at /home/brussell/bot-chan/node_modules/ws/lib/Receiver.js:508:14
       at Receiver.flush (/home/brussell/bot-chan/node_modules/ws/lib/Receiver.js:347:3)
       at Receiver.opcodes.1.finish (/home/brussell/bot-chan/node_modules/ws/lib/Receiver.js:541:12)

[located here](https://github.com/hydrabolt/discord.js/blob/indev/lib/Client/InternalClient.js#L2351)

I don't know why I'm getting this event but it's causing errors ¯\\\_(ツ)\_/¯

**Comment by abalabahaha** [comment]
#321
