### ISSUE TITLE
error recieving message

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#347]
```
pvpcraft-14 TypeError: Cannot read property 'id' of null
pvpcraft-14     at WebSocket.websocket.onmessage (/Bots/pvpcraft/node_modules/discord.js/lib/Client/InternalClient.js:2240:48)
pvpcraft-14     at WebSocket.onMessage (/Bots/pvpcraft/node_modules/ws/lib/WebSocket.js:442:14)
pvpcraft-14     at emitTwo (events.js:111:20)
pvpcraft-14     at WebSocket.emit (events.js:191:7)
pvpcraft-14     at Receiver.ontext (/Bots/pvpcraft/node_modules/ws/lib/WebSocket.js:841:10)
pvpcraft-14     at /Bots/pvpcraft/node_modules/ws/lib/Receiver.js:536:18
pvpcraft-14     at Receiver.applyExtensions (/Bots/pvpcraft/node_modules/ws/lib/Receiver.js:371:5)
pvpcraft-14     at /Bots/pvpcraft/node_modules/ws/lib/Receiver.js:508:14
pvpcraft-14     at Receiver.flush (/Bots/pvpcraft/node_modules/ws/lib/Receiver.js:347:3)
pvpcraft-14     at Receiver.opcodes.1.finish (/Bots/pvpcraft/node_modules/ws/lib/Receiver.js:541:12)
```
Not sure if this is a problem with my code but it look's like it may be an issue with the lib. Not on latest but it's close.

**Comment by GexoXYZ** [comment]
lib/Client/InternalClient.js:2240:48 is nowhere near onMessage though

**Comment by macdja38** [comment]
I'll look into it, idk how old the version was, forgot non does not update from git unless you force it to.
