### ISSUE TITLE
Discord.js crashes on .addMemberToRole.

### ISSUE THREAD

**Issue by Winneon** [hydrabolt/discord.js#369]
Hello,

I've run into a role update issue these past few days. I've tried the Discord API server but my question never seems to get answered, so I guess I'll try to sort it out here. Every time I run .addMemberToRole or its alias (.addUserToRole), the client crashes. To test what specifically what was crashing, I ran this snippet here. Both IDs were received by printing out the `servers` attribute.

```
this.bot.addUserToRole("87353905251377152", "182354064439246848", (error) => {
	if (error){
		console.log("An error occurred adding the host to the channel role.");
		console.log(error);
	} else {
		console.log("yeh");
	}
});
```

This is the error I get:

```
TypeError: Cannot read property 'id' of null
    at O:\dev\js\shows.js\server\node_modules\discord.js\lib\Client\InternalClient.js:58:704
    at Array.map (native)
    at InternalClient.addMemberToRole (O:\dev\js\shows.js\server\node_modules\discord.js\lib\Client\InternalClient.js:58:680)
    at Client.addMemberToRole (O:\dev\js\shows.js\server\node_modules\discord.js\lib\Client\Client.js:393:198)
    at Client.addUserToRole (O:\dev\js\shows.js\server\node_modules\discord.js\lib\Client\Client.js:394:185)
    at Client.<anonymous> (O:\dev\js\shows.js\server\bot.js:29:12)
    at emitNone (events.js:67:13)
    at Client.emit (events.js:166:7)
    at InternalClient.checkReady (O:\dev\js\shows.js\server\node_modules\discord.js\lib\Client\InternalClient.js:14:752)
    at null._onTimeout (O:\dev\js\shows.js\server\node_modules\discord.js\lib\Client\InternalClient.js:14:1051)
```

This seems to be on [this line here](https://github.com/hydrabolt/discord.js/blob/master/src/Client/InternalClient.js#L940), at r.id. The r variable, role (I believe), seems to be null. I'm not entirely sure what would be causing this issue.

**Comment by GexoXYZ** [comment]
Should be fixed on indev

**Comment by Winneon** [comment]
The error it returns on indev is Error: Forbidden. Both IDs are valid as I'm able to log into the bot and create roles with the bot, so the manage_roles perm is working fine.

**Comment by abalabahaha** [comment]
Bot's can only add people to roles that are at a lower position than their highest role

**Comment by Winneon** [comment]
The Bot role on my test server is the top role and has every perm though. The created roles are always below it in the role hierarchy.

**Comment by Winneon** [comment]
It randomly started working again after me not changing a thing. I don't know what happened. I'll re-open this issue if it occurs again.

**Comment by mawesome4ever** [comment]
Dang, i was having a similar issue. I was hoping you had a fix. ;/
