### ISSUE TITLE
Error on Bot Leaving Voice Channel

### ISSUE THREAD

**Issue by NewRasputin** [hydrabolt/discord.js#395]
It's saying that the voiceChannel.id of the message author is invalid when I try to make the bot leave the voice channel but it works fine for joining. Am I doing something wrong?

```
Error: invalid voice channel/connection to leave 
at InternalClient.leaveVoiceChannel (\node_modules\discord.js\lib\Client\InternalClient.js:4:825) 
at Client. leaveUoiceChannel (\node_modules\discord.js\lib\Client\Client.js:420:196) at Client.<anonymous> (\Documents\Visual Studio 2015\Projects\discordbot\discordbot\app.js:12:15) 
at emitOne (events.js:96:13) 
at Client.emit (events.js:188:7) at WebSocket.InternalClient.createWS.url.websocket.onmessage (\node_modules\discord.js\lib\Client\InternalClient.js:90:15) 
at WebSocket.onMessage (\node_modules\ws\lib\WebSocket.js:4 42:14) 
at emitTwo (events.js:111:20) 
at WebSocket.emit (events.js:191:7) 
at Receiver.ontext (\node_modules\ws\libWebSocket_js:841:1 0) 
```

My code

```
var Discord = require("discord.js");
var mybot = new Discord.Client();

mybot.on("message", function (message) {
    if (message.content === "!joincall") {
        mybot.joinVoiceChannel(message.author.voiceChannel.id);
    }
    if (message.content === "!leavecall") {
        mybot.leaveVoiceChannel(message.author.voiceChannel.id, function (error {console.log(error)});
    }
});

mybot.loginWithToken("token");
```

**Comment by briantanner** [comment]
Are you still in the voice channel when you run that command?
Also, you can just send `message.author.voiceChannel` instead of adding `.id`

**Comment by NewRasputin** [comment]
Yep, I sure am, and by removing the .id it works now. Thanks!
