### ISSUE TITLE
TokenCacher fallback to /tmp

### ISSUE THREAD

**Issue by SpencerSharkey** [hydrabolt/discord.js#405]
I am using Discord.js on AWS Lambda which does not provide write access to any of the directories listed in the TokenCacher. (located @ [/lib/Util/TokenCacher.js](https://github.com/hydrabolt/discord.js/blob/master/lib/Util/TokenCacher.js))

This caused discord.js to error out during the login process, with a bit of a non-explanatory error:
`Error: Uncaught, unspecified "error" event. (undefined) at TokenCacher.emit (events.js:144:17) at error (/var/task/node_modules/discord.js/lib/Util/TokenCacher.js:12:185) at /var/task/node_modules/discord.js/lib/Util/TokenCacher.js:12:122 at FSReqWrap.oncomplete (fs.js:82:15)`

I know this is platform specific, but I believe /tmp is a good fallback. Lambda grants privileges to that directory.

I'll submit a PR shortly to add /tmp to the list, but I was wondering if anyone had security concerns.

**Comment by SpencerSharkey** [comment]
Thank you!
