### ISSUE TITLE
Cannot find module 'ws'

### ISSUE THREAD

**Issue by ThatOneGuyOnline** [hydrabolt/discord.js#444]
I get this error,

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fazebigboy/node_modules/discord.js/lib/Client/InternalClient.js:1:957)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

this is my code,

var Discord = require("discord.js");

var bot = new Discord.Client();

bot.on("message", function(message){
	if(message.content === "no"){
		bot.reply(message,"sorry xd");
	}
});

bot.login("email","password");

I'm on a mac, if that's the problem then rip

**Comment by abalabahaha** [comment]
Are you sure you typed `npm install discord.js` in your bot folder?

**Comment by hydrabolt** [comment]
did any errors occur when installing discord.js?

**Comment by staentomic** [comment]
Try doing **npm install discord.js** again and make sure that your node is **updated**

**Comment by abalabahaha** [comment]
Closing due to inactivity
