### ISSUE TITLE
Bot won't leave voicechannel after playback

### ISSUE THREAD

**Issue by SquirrelsMcGee** [hydrabolt/discord.js#445]
This bot was working fine a few days ago, but now the bot wont leave the voicechannel after playback, and subsequent attempts at playing files/videos after the first one wont work at all.
Here is part of the code i use;
```
mybot.leaveVoiceChannel(message.author.voiceChannel);
	mybot.joinVoiceChannel(message.author.voiceChannel, function(error, voice) {
		//console.log(message.author+" aka <"+message.author.username+"> attempted to play this url, <"+para+">");
		mybot.voiceConnection.playFile(para, soundOptions, function(error, intent) {
			intent.on("end", function() {
				mybot.leaveVoiceChannel(message.author.voiceChannel);
			});
		
		if (error) {
			mybot.voiceConnection.stopPlaying();
			mybot.leaveVoiceChannel(message.author.voiceChannel);
			console.log(error);
		}				
	});
});
```
The bot joins the voicechannel of the user who sent the command, and will join any voicechannel regardless of whether this bug is happening.
I also have gotten this error;
```
Error: No voice server details within 10 seconds
    at Timeout._onTimeout (C:\Users\Win 8 - Steer\node_modules\discord.js\lib\Client\InternalClient.js:397:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by Technoguyfication** [comment]
They addressed this is the API updates on the Discord API server. Hotfix is coming out tonight.

**Comment by SquirrelsMcGee** [comment]
Oh ok thank you, will close this issue
