### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by gaarb** [hydrabolt/discord.js#449]
Code
```
bot.on("message", (msg) => {
	//if message begins with "ping"
	if (msg.content.startsWith("ping")) {
		//send a message to the channel the ping message was sent in.
		bot.sendMessage(msg, "pong!");

		//alert the console
		console.log("pong-ed " + msg.author.username);
	}
});
```
Error
```
C:\Users\Gabriel\Documents\GitHub\toontown-rewritten-discord\node_modules\discord.js\lib\Client\Client.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";exports.__esModule = true;var _createClass=(function(){function defineProperties(target,props){for(var i=0;i < props.length;i++) {var descriptor=props[i];descriptor.enumerable = descriptor.enumerable || false;descriptor.configurable = true;if("value" in descriptor)descriptor.writable = true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};})();function _interopRequireDefault(obj){return obj && obj.__esModule?obj:{"default":obj};}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}function _inherits(subClass,superClass){if(typeof superCl

TypeError: Cannot call a class as a function
    at _classCallCheck (C:\Users\Gabriel\Documents\GitHub\toontown-rewritten-discord\node_modules\discord.js\lib\Client\Client.js:1:805)
    at Object.Client (C:\Users\Gabriel\Documents\GitHub\toontown-rewritten-discord\node_modules\discord.js\lib\Client\Client.js:17:103)
    at Object.<anonymous> (C:\Users\Gabriel\Documents\GitHub\toontown-rewritten-discord\discord-bot.js:12:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by abalabahaha** [comment]
Upgrade to NodeJS 0.12+

**Comment by gaarb** [comment]
I fixed the issue
