### ISSUE TITLE
Type Error when requiring discord.js

### ISSUE THREAD

**Issue by gr33nfury** [hydrabolt/discord.js#45]
I have tried install discord.js from npm install discord.js and I have cloned the repo in both cases I am never able to run a bot. I have python 2.7.6 installed and this is on Linux.

I followed this tutorial after install via npm and receive the below error.
http://discordjs.readthedocs.org/en/latest/create_simple_bot.html

```
*/node_modules/discord.js/lib/Client.js:2
){if(typeof superClass !== "function" && superClass !== null){throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (*/node_modules/discord.js/lib/Client.js:2:789)
    at */node_modules/discord.js/lib/Client.js:3:153
    at Object.<anonymous> (*/node_modules/discord.js/lib/Client.js:79:1927)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (*/node_modules/discord.js/lib/index.js:1:161)
```

**Comment by TehSeph** [comment]
Can we see you bot's code?

**Comment by gr33nfury** [comment]
It's the same code as that link I added

```
var Discord = require("discord.js");
var bot = new Discord.Client();

bot.on("message", function(message){

            if( message.content === "avatar me!" ){

        var usersAvatar = message.sender.avatarURL;

        if(usersAvatar){
            // user has an avatar

            bot.reply(message, "your avatar can be found at " + usersAvatar);

        }else{
            // user doesn't have an avatar

            bot.reply(message, "you don't have an avatar!");
        }

            }

} );

bot.login("your discord email", "your discord password");
```

**Comment by hydrabolt** [comment]
Hi, which version of node are you running on?

**Comment by gr33nfury** [comment]
Good question. I can get that information for you in about 8 hours.

**Comment by hydrabolt** [comment]
@gr33nfury Is the issue resolved?
