### ISSUE TITLE
Cannot read property 'queue' of undefined (Deleting Messages)

### ISSUE THREAD

**Issue by datitisev** [hydrabolt/discord.js#496]
## SCENARIO

I have a command that gets the channel logs, filters them to get the bot's messages, and then loops through them and deletes them one by one.
Code (removed debugs):
```js
Bot.getChannelLogs(msg.channel, (err, logs) => {
  if (err) return Bot.sendMessage(msg, 'Unable to clean messages :|');

  let botLogs = logs.filter(a => a.author.equals(Bot.user));

  botLogs.forEach(elem => {
    Bot.deleteMessage(elem).catch(err => error(err.stack));
  });
});
```

## Error

_(Replaced full path to project with `Bot`)_

```sh
TypeError: Cannot read property 'queue' of undefined
    at InternalClient.apiRequest (Bot/node_modules/discord.js/lib/Client/InternalClient.js:211:24)
    at Bot/node_modules/discord.js/lib/Client/InternalClient.js:858:19
    at process._tickCallback (internal/process/next_tick.js:103:7) 
```

## More Info

Gexo tried to solve the issue by replacing the for loop in `lib/Client/InternalClient` line 196 with 
```js
for(var bucket in buckets) {
  ++waitFor;
  this.buckets[bucket].queue(done);
}
```
but it still gave the same error (different line), and wouldn't even send messages (it sent them before).

The code works fine on `v8.0.0`,

**Comment by datitisev** [comment]
Fixed in latest `indev` somewhere somehow sometime ¯\\\_(ツ)_/¯
