### ISSUE TITLE
InternalClient error for status

### ISSUE THREAD

**Issue by renedx** [hydrabolt/discord.js#516]
Running the bot a while, it errors on this and I cannot seem to pin down the problem exactly.

Anyone ran into similar, something I'm doing wrong causing this?

```
/home/ec2-user/robot/node_modules/discord.js/lib/Client/InternalClient.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";exports.__esModule = true;var _createClass=(function(){function defineProperties(target,props){for(var i=0;i < props.length;i++) {var descriptor=props[i];descriptor.enumerable = descriptor.enumerable || false;descriptor.configurable = true;if("value" in descriptor)descriptor.writable = true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};})();function _interopRequireDefault(obj){return obj && obj.__esModule?obj:{"default":obj};}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}var _superagent=require("superagent");var _superagent2=_interopRequireDefault(_superage

TypeError: Cannot read property 'status' of undefined
    at /home/ec2-user/robot/node_modules/discord.js/lib/Client/InternalClient.js:1:5323
    at Request.callback (/home/ec2-user/robot/node_modules/superagent/lib/node/index.js:587:12)
    at ClientRequest.<anonymous> (/home/ec2-user/robot/node_modules/superagent/lib/node/index.js:539:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by macdja38** [comment]
any chance I could ask you to try out the latest indev branch?

**Comment by renedx** [comment]
I'll use dev, need to modify deploy for that first. Will report if issue persists :)

**Comment by roncli** [comment]
I was going to report this as well, and it indeed does look fixed in indev, checking for data's existence before going to data.status.

**Comment by renedx** [comment]
Indeed looks fixed in dev 👍
