### ISSUE TITLE
Error on trying to log in

### ISSUE THREAD

**Issue by aequasi** [hydrabolt/discord.js#53]
```
/Users/aaron/Projects/discord-server-list/js-bot/node_modules/discord.js/lib/Client.js:67
nce=_ref13;var user=self.getUser("id",presence.user.id);user.status = presence
                                                                    ^
TypeError: Cannot set property 'status' of null
    at Client.addServer (/Users/aaron/Projects/discord-server-list/js-bot/node_modules/discord.js/lib/Client.js:67:1249)
    at WebSocket.websocket.onmessage (/Users/aaron/Projects/discord-server-list/js-bot/node_modules/discord.js/lib/Client.js:41:425)
    at WebSocket.onMessage (/Users/aaron/Projects/discord-server-list/js-bot/node_modules/ws/lib/WebSocket.js:414:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/Users/aaron/Projects/discord-server-list/js-bot/node_modules/ws/lib/WebSocket.js:797:10)
    at /Users/aaron/Projects/discord-server-list/js-bot/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/Users/aaron/Projects/discord-server-list/js-bot/node_modules/ws/lib/Receiver.js:360:5)
    at /Users/aaron/Projects/discord-server-list/js-bot/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/Users/aaron/Projects/discord-server-list/js-bot/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.1.finish (/Users/aaron/Projects/discord-server-list/js-bot/node_modules/ws/lib/Receiver.js:478:12)
```

Not sure what's happening

**Comment by hydrabolt** [comment]
Not really sure myself what is going on here, but all the issues lingering in 4.1.1 and below are being fixed in version 5.0.0, which can be found in the rewrite branch! It's currently undocumented, but I _think_ all of the features are present. If you need help, feel free to ask!
