### ISSUE TITLE
How to mention users when writing a command ?

### ISSUE THREAD

**Issue by Takatsukii** [hydrabolt/discord.js#546]
As an answer, this is what I'm currently using;

if(message.content === "t!hello Takatsuki")
	{
		bot.reply(message, "Hi there!");
	}

However, I want it to work so that instead of typing my name, I can just mention the Discord user (@Takatsuki).

**Comment by TehTotalPwnage** [comment]
You can just use a user object to mention a user, as in the example below.

`bot.sendMessage(message.channel, message.author + ", Hi there!");`

message.author is the object here.

To get a user object, you would have to get it out of the cache. See the page on Caches in the documentation.

**Comment by Takatsukii** [comment]
Well I'm doing something wrong. 

I tried the user object, and it's not working how I wanted it. More likely than not because of my wording. 
http://i.imgur.com/Q8EXdyv.png <--I want the third line to work like the first line. 

So then I tried this; 
`client.users.get("id", 11238414);

	 client.channels.getAll("name", "general");

But all I got in return was; 
``client.users.get("id", 11238414);
         ^

ReferenceError: client is not defined
    at Client.<anonymous> (C:\Users\Kyle\Desktop\bot.js:9:3)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (C:\Users\Kyle\node_modules\discord.js\lib\Client\InternalClient.js:101:15)
    at WebSocket.onMessage (C:\Users\Kyle\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\Kyle\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\Users\Kyle\node_modules\discord.js\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\Users\Kyle\node_modules\discord.js\node_modules\ws\lib\Receiver.js:371:5)`

**Comment by eslachance** [comment]
Please join the discord-api server where we can troubleshoot without being spammed by our github bot. [https://discord.gg/2pEaC](https://discord.gg/2pEaC)
