### ISSUE TITLE
Using stopPlaying() while a video directly streamed from ytdl is playing causes a crash

### ISSUE THREAD

**Issue by meew0** [hydrabolt/discord.js#60]
The crash report:
```
/home/miras/Projects/lethe/node_modules/discord.js/lib/Voice/VoiceConnection.js:71
			this.instream.destroy();
			              ^

TypeError: this.instream.destroy is not a function
    at VoiceConnection.stopPlaying (/home/miras/Projects/lethe/node_modules/discord.js/lib/Voice/VoiceConnection.js:71:18)
    at playStopped (/home/miras/Projects/lethe/lethe.js:303:72)
    at Client.<anonymous> (/home/miras/Projects/lethe/lethe.js:71:5)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (/home/miras/Projects/lethe/node_modules/discord.js/lib/Client/InternalClient.js:1056:14)
    at WebSocket.onMessage (/home/miras/Projects/lethe/node_modules/ws/lib/WebSocket.js:414:14)
    at emitTwo (events.js:92:20)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/home/miras/Projects/lethe/node_modules/ws/lib/WebSocket.js:797:10)
```

Offending lines of code:
https://github.com/meew0/Lethe/blob/adcf966759bc685e9d38ddf6a57af49b3bb34685/lethe.js#L303 (stream is stopped)
https://github.com/meew0/Lethe/blob/adcf966759bc685e9d38ddf6a57af49b3bb34685/lib/youtube-stream.js#L11 (stream is requested)
https://github.com/fent/node-ytdl-core/blob/master/lib/index.js#L26 (stream is created)

**Comment by SimonSchick** [comment]
the `destroy()` method is not standardised and only works for file stream.
