### ISSUE TITLE
TypeError: id is not a function (for Collection.find)

### ISSUE THREAD

**Issue by timhwang21** [hydrabolt/discord.js#627]
Error:

```
[12:51]timothy~/Github/RickBot-master->node index.js
/Users/timothy/Github/RickBot/index.js:27
const myChannel = bot.channels.find('id', Auth.channels.meta);
                               ^

TypeError: id is not a function
    at Cache.find (native)
    at Object.<anonymous> (/Users/timothy/Github/RickBot/index.js:27:32)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

My code:

```javascript
const myChannel = bot.channels.find('id', Auth.channels.meta);
```

My understanding is that `.channels` returns an instance of `Collection`. I couldn't find anything immediately obvious [here](https://github.com/hydrabolt/discord.js/blob/master/src/util/Collection.js#L87). Thanks!

**Comment by acdenisSK** [comment]
Sure that you are in discord.js@9.1.0? As `Cache` doesn't exist in 9.1.0 at all.

**Comment by timhwang21** [comment]
I'm on `@8.1.0.` Thanks for pointing that out!

**Comment by timhwang21** [comment]
Sorry, is there a 9.1.0?

```
npm ERR! Valid install targets:
npm ERR! 9.0.2, 9.0.1, 9.0.0, 8.1.0, 8.0.0, 7.0.1, 7.0.0, 6.1.0, 6.0.0, 5.3.2, 5.3.1, 5.3.0, 5.2.0, 5.1.0, 5.0.1, 5.0.0, 4.1.1, 4.1.0, 4.0.0, 3.10.2, 3.10.1, 3.10.0, 3.9.1, 3.9.0, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.2, 3.7.1, 3.7.0, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.0, 3.4.2, 3.4.1, 3.4.0, 3.3.4, 3.3.3, 3.3.2, 3.3.1, 3.3.0, 3.2.1, 3.2.0, 3.1.6, 3.1.5, 3.1.4, 3.1.3, 3.1.2, 3.1.1, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.7.2, 2.7.1, 2.7.0, 2.6.8, 2.6.7, 2.6.6, 2.6.5, 2.6.4, 2.6.3, 2.6.2, 2.6.1, 2.6.0, 2.5.0, 2.4.2, 2.4.1, 2.4.0, 2.3.1, 2.3.0, 2.2.2, 2.2.1, 2.2.0, 2.1.1, 2.1.0, 2.0.2, 2.0.1, 2.0.0, 1.2.2, 1.2.1, 1.1.0, 1.0.2, 1.0.1
```

**Comment by acdenisSK** [comment]
Uh woops, meant 9.0.2*
Thought there was 9.1.0 😐

**Comment by timhwang21** [comment]
Thanks!
