### ISSUE TITLE
EPIPE error when ending a streamdispatcher

### ISSUE THREAD

**Issue by MikaalSky** [hydrabolt/discord.js#635]
```
Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:706:26)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at onwrite (_stream_writable.js:346:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:807:12)
```

Basically occurs whenever closing a StreamDispatcher with .end();. It's not 100% but it does happen.

**Comment by Gawdl3y** [comment]
Fixed by #662.
