### ISSUE TITLE
loginWithToken is not a function

### ISSUE THREAD

**Issue by Bluethefurry** [hydrabolt/discord.js#659]
```
/root/dscrd/him.js:773
c.loginWithToken(config.token,"","")
  ^

TypeError: c.loginWithToken is not a function
    at Object.<anonymous> (/root/dscrd/him.js:773:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

This is my bot's starting code:
```

Discord=require("discord.js");
var config = require("./config.json")
var enableOptional = config.enableOptional
var logfile = config.logfile

c.loginWithToken(config.token,"","")
```
Any ideas why this is happening? :/

**Comment by Hyper-Coder** [comment]
It isn't supposed to be a function and it will not be added. Read the documentation.

**Comment by eslachance** [comment]
Because if you read the docs you will see that version 9 has changed that to `client.login()`

**Comment by Bluethefurry** [comment]
Thanks, i didnt know that discord.js got updated, i just reinstalled my server so i was confused why it didnt work anymore!

**Comment by FrankenMan** [comment]
Kind sir, are you aware of the documentation

**Comment by Bluethefurry** [comment]
@FrankenMan see what i literally just posed
