### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by a09hopper** [hydrabolt/discord.js#681]
I keep getting this error even with a tutorial or just var Discord = require("discord.js")
`C:\Users\agh26\node_modules\discord.js\src\client\Client.js:17
class Client extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\agh26\node_modules\discord.js\src\index.js:2:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

**Comment by Trismirite** [comment]
install node v6

**Comment by Gawdl3y** [comment]
**Node 6.0.0 or newer is required.**
