### ISSUE TITLE
401 Unauthorized when sending a message

### ISSUE THREAD

**Issue by BitBitmap** [hydrabolt/discord.js#683]
Hi,

When my bot triggers `mybot.sendMessage(message.channel, "message")`, it gives me the stack trace below. The bot has been able to reply back to messages recently up until now. I checked with a test server to see if it's really a permission error but the bot was unable to post a message even after giving it full privs. I authenticate using `mybot.loginWithToken("YOUR KEY");`.

```error:
      { Error: cannot POST /api/channels/224357310426775553/messages (401)
          at Response.toError (/home/baka/Squidward-Bot/node_modules/discord.js/node_modules/superagent/lib/node/response.js:106:13)
          at Response.setStatusProperties (/home/baka/Squidward-Bot/node_modules/discord.js/node_modules/superagent/lib/node/response.js:183:12)
          at new Response (/home/baka/Squidward-Bot/node_modules/discord.js/node_modules/superagent/lib/node/response.js:42:8)
          at IncomingMessage.<anonymous> (/home/baka/Squidward-Bot/node_modules/discord.js/node_modules/superagent/lib/node/index.js:918:22)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:934:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickCallback (internal/process/next_tick.js:98:9)
        status: 401,
        text: '{"code": 0, "message": "401: Unauthorized"}',
        method: 'POST',
        path: '/api/channels/224357310426775553/messages' },
```

**Comment by eslachance** [comment]
There was a change in the API that prevented v8 bots from working anymore. A special branch was put in place. Simply run this and restart your bot: 

`npm i --save hydrabolt/discord.js#indev-old` (note that you require git to be installed for this to work).

**Comment by BitBitmap** [comment]
It works, thanks. Can you link me the API change notice that caused this?

**Comment by eslachance** [comment]
Yep, that was https://github.com/hammerandchisel/discord-api-docs/issues/119
The change *was* applied on an indev branch but that was never pushed to the main master branch before 9.0.0 was released, leading to this unfortunate "other branch" situation. Indev-old also gives some additional bug fixes while it's at it.

**Comment by BitBitmap** [comment]
Got it. I'm assuming that this branch is still in development. Do you have an ETA for when will it get pushed to prod?

**Comment by eslachance** [comment]
This will not be pushed to prod. It is an emergency branch for version 8, but 8 is no longer globally maintained. We strongly suggest moving your code over to version 9 (knowing that it's a rewrite and requires a lot of code refactoring). We cannot guarantee how long v8 will continue working since it uses an older gateway version (3) which could, theoretically, stop working at any time.

**Comment by macdja38** [comment]
Just to update this information... v8 branch has been updated in npm as well and uses gateway v6 now.
