### ISSUE TITLE
setPlayingGame doesnt work

### ISSUE THREAD

**Issue by DarkN-exus** [hydrabolt/discord.js#692]
I have this code on the bot.on ready
`bot.on('ready', () => {
  console.log('All systems are operational');
  bot.setPlayingGame("Coding in progress!");
});`
And it gives me this error

```
  bot.setPlayingGame("Coding in progress!");
      ^

TypeError: bot.setPlayingGame is not a function
    at Client.bot.on (C:\Users\Nexus\Desktop\DarkBot MK.I\darkbot.js:9:7)
    at emitNone (events.js:91:20)
    at Client.emit (events.js:185:7)
    at WebSocketManager._emitReady (C:\Users\Nexus\node_modules\discord.js\src\c
lient\websocket\WebSocketManager.js:207:17)
    at WebSocketManager.checkIfReady (C:\Users\Nexus\node_modules\discord.js\src
\client\websocket\WebSocketManager.js:232:14)
    at GuildCreateHandler.handle (C:\Users\Nexus\node_modules\discord.js\src\cli
ent\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (C:\Users\Nexus\node_modules\discord.js\src
\client\websocket\packets\WebSocketPacketManager.js:93:65)
    at WebSocketManager.eventMessage (C:\Users\Nexus\node_modules\discord.js\src
\client\websocket\WebSocketManager.js:182:31)
    at WebSocket.ws.onmessage (C:\Users\Nexus\node_modules\discord.js\src\client
\websocket\WebSocketManager.js:65:37)
    at WebSocket.onMessage (C:\Users\Nexus\node_modules\ws\lib\WebSocket.js:442:
14)


```

**Comment by straighto** [comment]
in v9, ```bot.setPlayingGame("idk")``` was changed to ```bot.user.setStatus("online", "game")```

**Comment by iCrawl** [comment]
(╯°□°）╯︵ ┻━┻
Because it is not a function anymore.
https://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/ClientUser?scrollto=setStatus

**Comment by DarkN-exus** [comment]
Oh,i was using it from a previous version.Thanks
