### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by monster860** [hydrabolt/discord.js#718]
```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/monster860/discord_bot/node_modules/discord.js/src/index.js:1:91)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by hydrabolt** [comment]
Are you using node.js 6+?

**Comment by monster860** [comment]
Well, that fixes it
