### ISSUE TITLE
V8 Cannot read property forEach of undefined

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#746]
```
pvpcraft-1 (err): TypeError: Cannot read property 'forEach' of undefined
pvpcraft-1 (err):     at new Server (/docker/pvpcraft/pvpcraft/node_modules/discord.js/lib/Structures/Server.js:117:16)
pvpcraft-1 (err):     at InternalClient.processPacket (/docker/pvpcraft/pvpcraft/node_modules/discord.js/lib/Client/InternalClient.js:2219:23)
pvpcraft-1 (err):     at WebSocket.websocket.onmessage (/docker/pvpcraft/pvpcraft/node_modules/discord.js/lib/Client/InternalClient.js:1897:14)
pvpcraft-1 (err):     at WebSocket.onMessage (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/WebSocket.js:442:14)
pvpcraft-1 (err):     at emitTwo (events.js:106:13)
pvpcraft-1 (err):     at WebSocket.emit (events.js:191:7)
pvpcraft-1 (err):     at Receiver.ontext (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/WebSocket.js:841:10)
pvpcraft-1 (err):     at /docker/pvpcraft/pvpcraft/node_modules/ws/lib/Receiver.js:536:18
pvpcraft-1 (err):     at Receiver.applyExtensions (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/Receiver.js:371:5)
pvpcraft-1 (err):     at /docker/pvpcraft/pvpcraft/node_modules/ws/lib/Receiver.js:508:14
pvpcraft-1 (err):     at Receiver.flush (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/Receiver.js:347:3)
pvpcraft-1 (err):     at Receiver.opcodes.1.finish (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/Receiver.js:541:12)
pvpcraft-1 (err):     at Receiver.expectHandler (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/Receiver.js:499:31)
pvpcraft-1 (err):     at Receiver.add (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/Receiver.js:103:24)
pvpcraft-1 (err):     at TLSSocket.realHandler (/docker/pvpcraft/pvpcraft/node_modules/ws/lib/WebSocket.js:825:20)
pvpcraft-1 (err):     at emitOne (events.js:96:13)
pvpcraft-1 (err):     at TLSSocket.emit (events.js:188:7)
pvpcraft-1 (err):     at readableAddChunk (_stream_readable.js:177:18)
pvpcraft-1 (err):     at TLSSocket.Readable.push (_stream_readable.js:135:10)
pvpcraft-1 (err):     at TLSWrap.onread (net.js:542:20)
```

**Comment by abalabahaha** [comment]
d22ca96 should prevent this
