### ISSUE TITLE
class Client extends EventEmitter error

### ISSUE THREAD

**Issue by Kradre** [hydrabolt/discord.js#767]
class Client extends EventEmitter {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/node_modules/discord.js/src/index.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by iCrawl** [comment]
Update to Node v6
https://nodejs.org/en/
or
https://nodejs.org/en/download/package-manager/

**Comment by Kradre** [comment]
Thanks!

**Comment by GusCaplan** [comment]
@Kradre if this fixed your problem please make sure you close the issue. Thanks 😄 .
