### ISSUE TITLE
Latest update causes syntax error

### ISSUE THREAD

**Issue by egee-irl** [hydrabolt/discord.js#868]
The latest update causes an error:

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

This error is easily bypassed by using the --use_strict parameter. However, another error is thrown:

`SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (~/my-bot/node_modules/discord.js/src/index.js:2:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`

**Comment by Gawdl3y** [comment]
Upgrade Node to 6.0.0 or newer.
