### ISSUE TITLE
Mention user

### ISSUE THREAD

**Issue by CaptainArghh** [hydrabolt/discord.js#899]
```
var Discord = require("discord.js");

var bot = new Discord.Client();

bot.on ("message", function(message)
{
	var messagee = message.content.toLowerCase();
	if(messagee == "hi")
    {
        message.channel.sendMessage ("hi");
}
		else if(messagee === "hello") 
	{
		message.channel.sendMessage("Greetings" + " " + message.sender.mention());
}
});
```

Instead of it saying just "Greetings", I would like it to mention user aswell. How do I do that? I tried using 
`message.channel.sendMessage("Greetings" + " " + msg.sender.mention());`
but this didn't work that well.. Probably completely wrong so that's why I'm here asking for help. Quite new to all of this but figured trying to create a Discord Bot is a good place to start..

**Comment by CaptainArghh** [comment]
I should add that the error I get is
`           message.channel.sendMessage("Greetings" + " " + message.sender.mention());
                                                                                                                       ^

TypeError: Cannot read property 'mention' of undefined
    at Client.<anonymous> (C:\Users\espen\Documents\AkatoshBot.js:14:65)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (C:\Users\espen\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\espen\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:100:65)
    at WebSocketManager.eventMessage (C:\Users\espen\node_modules\discord.js\src\client\websocket\WebSocketManager.js:225:31)
    at WebSocket.ws.onmessage (C:\Users\espen\node_modules\discord.js\src\client\websocket\WebSocketManager.js:83:37)
    at WebSocket.onMessage (C:\Users\espen\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)`

**Comment by hydrabolt** [comment]
You're looking for [`message.author`](https://discord.js.org/#!/docs/tag/master/class/Message?scrollto=author), not `message.sender`.

It's also `message.author.toString()` (or just concatenate the user with a string)
