### ISSUE TITLE
Error updating guild member presence

### ISSUE THREAD

**Issue by CryptoCurrencyStuff** [hydrabolt/discord.js#937]
/discord.js/src/structures/Guild.js:783
    if (this.presences.get(id)) {
                      ^

TypeError: Cannot read property 'get' of undefined
    at Guild._setPresence (/discord.js/src/structures/Guild.js:783:23)
    at PresenceUpdateHandler.handle (/discord.js/src/client/websocket/packets/handlers/PresenceUpdate.js:46:15)
    at WebSocketPacketManager.handle (/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:100:65)
    at queue.forEach (/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:60:12)
    at Array.forEach (native)
    at WebSocketPacketManager.handleQueue (/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:59:16)
    at WebSocketManager._emitReady (/discord.js/src/client/websocket/WebSocketManager.js:249:24)
    at client.setTimeout (/discord.js/src/client/websocket/packets/handlers/Ready.js:51:45)
    at Timeout.setTimeout (/discord.js/src/client/Client.js:329:7)
    at ontimeout (timers.js:365:14)

**Comment by hydrabolt** [comment]
Fixed in https://github.com/hydrabolt/discord.js/commit/6043a1f83a70d95803c0f9c9ef8a4edc8dc09a97, available on indev! Thanks for finding this 👍
