### ISSUE TITLE
client.login(token); error

### ISSUE THREAD

**Issue by Kertopher** [hydrabolt/discord.js#938]
I'm not sure at all why this is happening. The other day, the code was working fine. I checked to see if my bot's token key changed (which it did and I did replace) but the error persists. I also remade a token and nothing changed.

 I added a .catch() to it and it seems that the discord server isn't liking me. The node.js error is "Bad request."

I looked through what the catch error sent me and I found this:

```
error:
      { Error: cannot POST /api/auth/login (400)
          at Response.toError (C:\ndjs\Discord\node_modules\superagent\lib\node\response.js:106:13)
          at Response.setStatusProperties (C:\ndjs\Discord\node_modules\superagent\lib\node\response.js:183:12)
          at new Response (C:\ndjs\Discord\node_modules\superagent\lib\node\response.js:42:8)
          at IncomingMessage.<anonymous> (C:\ndjs\Discord\node_modules\superagent\lib\node\index.js:918:22)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickCallback (internal/process/next_tick.js:98:9)
        status: 400,
        text: '{"email": ["Not a well formed email address."], "password": ["This field is required."]}',
        method: 'POST',
        path: '/api/auth/login' }
```

And here's the code that calls the thing. Removed token for obvious reasons.
```
client.login('removed token for git').catch((error) => {
	console.log(error)
  });
```

Can anyone tell me what stupid thing I'm doing? Or is this not my fault? Help is greatly appreciated.

EDIT: Pretty sure I'm using 7.0.0. Just ran `npm install --save` again. Nothing changed.

**Comment by Kertopher** [comment]
Of course. I just checked the lastest version and it's 10.0.1. Not sure were I got 7.0.0 from. Wow. Gg. Of course login won't accept the token.
